'use client'
import {useState,useEffect,useRef} from 'react'
import {useRouter} from 'next/navigation'
import {linkedChequeOperation,type CheckOperationInput,type CheckAccountingPreview} from './check-lifecycle-actions'
import {businessDay} from '@/lib/dashboard/simple-metrics'
export interface LinkedCheck {id:string;check_number:string;amount:number;currency:string}
type Pending={id:string;input:CheckOperationInput;check:LinkedCheck}
export default function LinkedChequeOperation({storeId,selection,banks,boxes,onClose,previewOnly=false,previewData}:{storeId:string;selection:{check:LinkedCheck;opType:string}|null;banks:{id:string;bank_name:string;account_number:string}[];boxes:{id:string;name:string;type?:string}[];onClose:()=>void;previewOnly?:boolean;previewData?:CheckAccountingPreview}){
 const router=useRouter(),pending=useRef<Pending|null>(null),flight=useRef(false);
 const [check,setCheck]=useState<LinkedCheck|null>(null),[input,setInput]=useState<CheckOperationInput>({checkId:'',operationType:'collect',operationDate:businessDay().date,notes:''}),[mode,setMode]=useState('cash'),[review,setReview]=useState<CheckAccountingPreview|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[error,setError]=useState('');
 const key=`linked-cheque-operation:${storeId}`;
 useEffect(()=>{if(previewOnly)return;try{const raw=sessionStorage.getItem(key);if(!raw)return;const p=JSON.parse(raw);if(!p.check?.id||!p.input||p.input.checkId!==p.check.id||!['collect','return_to_customer'].includes(p.input.operationType)||!['operationDate','checkId'].every(k=>typeof p.input[k]==='string')||!/^([\da-f]{8}-)([\da-f]{4}-){3}[\da-f]{12}$/i.test(p.id))throw Error();pending.current=p;setCheck(p.check);setInput(p.input);setMode(p.input.targetBankAccountId?'bank':'cash');setUncertain(true);setError('طلب سابق غير مؤكد؛ أعد محاولة الطلب نفسه قبل إجراء عملية أخرى')}catch{setUncertain(true);setError('تعذر قراءة الطلب السابق؛ تحقق من نتيجته قبل تسجيل عملية أخرى');setCheck({id:'',check_number:'طلب سابق',amount:0,currency:''})}},[key,previewOnly]);
 useEffect(()=>{if(!selection||pending.current||uncertain)return;setCheck(selection.check);setInput({checkId:selection.check.id,operationType:selection.opType as CheckOperationInput['operationType'],operationDate:businessDay().date,notes:''});setReview(null);setError('');setMode('cash')},[selection,uncertain]);
 function change(p:Partial<CheckOperationInput>){if(busy||uncertain)return;pending.current=null;setInput(v=>({...v,...p}));setReview(null);setError('')}
 async function inspect(){if(flight.current)return;flight.current=true;setBusy(true);setError('');try{if(previewOnly&&previewData){setReview({...previewData,date:input.operationDate,operationType:input.operationType});return}const r=await linkedChequeOperation(input,crypto.randomUUID(),false);setReview(r.preview||null);if(!r.success)setError(r.error||'تعذر تحميل المعاينة')}finally{flight.current=false;setBusy(false)}}
 async function save(){if(flight.current||previewOnly||!check||(!review&&!pending.current))return;if(!pending.current)pending.current={id:crypto.randomUUID(),input:{...input},check:{...check}};flight.current=true;setBusy(true);setError('');
 try{try{sessionStorage.setItem(key,JSON.stringify(pending.current))}catch{setError('تعذر حفظ معرف الطلب؛ لم تُرسل العملية');return}
 const r=await linkedChequeOperation(pending.current.input,pending.current.id,true);
 if(r.success){pending.current=null;try{sessionStorage.removeItem(key)}catch{}setUncertain(false);setCheck(null);setReview(null);onClose();router.refresh()}
 else{setError(r.error||'تعذر التنفيذ');setUncertain(uncertain||!!r.uncertain);if(!uncertain&&!r.uncertain){pending.current=null;try{sessionStorage.removeItem(key)}catch{}setReview(null)}}
 }catch{setUncertain(true);setError('تعذر تأكيد النتيجة؛ أعد محاولة الطلب نفسه')}finally{flight.current=false;setBusy(false)}}
 if(!check)return null;
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm" dir="rtl"><section role="dialog" aria-modal="true" aria-labelledby="linked-check-title" className="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-sky-500/30 bg-slate-900 p-5 space-y-4 text-slate-100"><header className="flex justify-between gap-4"><h2 id="linked-check-title" className="text-xl font-bold">{input.operationType==='collect'?'تحصيل شيك مرتبط':'إعادة شيك للمصدر'}</h2><button aria-label="إغلاق عملية الشيك المرتبط" disabled={busy||uncertain} onClick={()=>{setCheck(null);setReview(null);onClose()}}>×</button></header><p>الشيك #{check.check_number} · {Number(check.amount).toFixed(2)} {check.currency}</p><p className="text-sm text-sky-200 bg-sky-500/10 rounded-xl p-3">{input.operationType==='collect'?'ينقل التحصيل القيمة من المحفظة إلى النقد أو البنك، دون دفعة ثانية على حساب العميل.':'تعكس الإعادة تسوية هذا الشيك وتعيد ذمة العميل والمتبقي على الفاتورة، دون صرف نقدي.'}</p>
 <fieldset disabled={busy||uncertain} className="space-y-4"><label className="block">تاريخ العملية<input aria-label="تاريخ عملية الشيك المرتبط" type="date" className="block w-full rounded-xl p-3 bg-slate-800 mt-2" value={input.operationDate} onChange={e=>change({operationDate:e.target.value})} onBlur={e=>{if(e.target.value!==input.operationDate)change({operationDate:e.target.value})}}/></label>
 {input.operationType==='collect'&&<><label className="block">وجهة التحصيل<select aria-label="وجهة تحصيل الشيك المرتبط" value={mode} className="block w-full rounded-xl p-3 bg-slate-800 mt-2" onChange={e=>{setMode(e.target.value);change({targetCashBoxId:'',targetBankAccountId:''})}}><option value="cash">صندوق نقدي</option><option value="bank">حساب بنكي</option></select></label><label className="block">{mode==='cash'?'الصندوق':'الحساب البنكي'}<select aria-label="حساب تحصيل الشيك المرتبط" value={mode==='cash'?input.targetCashBoxId||'':input.targetBankAccountId||''} className="block w-full rounded-xl p-3 bg-slate-800 mt-2" onChange={e=>change(mode==='cash'?{targetCashBoxId:e.target.value,targetBankAccountId:''}:{targetBankAccountId:e.target.value,targetCashBoxId:''})}><option value="">اختر وجهة نشطة بعملة الشيك</option>{mode==='cash'?boxes.filter(b=>!b.type||b.type==='cash').map(b=><option key={b.id} value={b.id}>{b.name}</option>):banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} — {b.account_number}</option>)}</select></label></>}
 <label className="block">ملاحظة (اختياري)<textarea aria-label="ملاحظة عملية الشيك المرتبط" className="block w-full rounded-xl p-3 bg-slate-800 mt-2" maxLength={1000} value={input.notes||''} onChange={e=>change({notes:e.target.value})}/></label><button onClick={inspect} className="w-full rounded-xl border border-sky-500 p-3">مراجعة القيد الفعلي</button></fieldset>
 {review&&!uncertain&&<div role="status" className="rounded-xl bg-sky-500/10 border border-sky-500/30 p-4 space-y-2"><p>مدين: {review.debitAccountCode} — {review.debitAccountName}</p><p>دائن: {review.creditAccountCode} — {review.creditAccountName}</p><strong>{review.amount.toFixed(2)} {review.currency}</strong><p className="text-sm">المراجعة لا تغيّر الأرصدة.</p></div>}{error&&<p role="alert" className="text-amber-300">{error}</p>}<button disabled={previewOnly||busy||(!review&&!pending.current)||(!pending.current&&uncertain)} onClick={save} className="w-full rounded-xl bg-emerald-500 p-3 text-slate-950 font-bold disabled:opacity-40">{previewOnly?'معاينة فقط — لا حفظ مالي':busy?'جارٍ التحقق…':uncertain?'إعادة محاولة الطلب نفسه':'اعتماد العملية'}</button><p className="text-xs text-slate-400">للـمالك أو المدير. الإيداع والتجيير والارتداد اللاحق خارج هذا المسار.</p></section></div>
}
