const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),m={exports:{}}
new Function('exports','module',ts.transpileModule(fs.readFileSync('lib/invoices/list-presentation.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(m.exports,m)
const {invoiceListView,normalizeInvoiceFilters,invoicePaymentKind,invoiceOverdue,invoiceExportRows}=m.exports
const row=(id,status,total,paid,extra={})=>({id,invoice_number:'INV-'+id,customer_id:'customer',customer_name:'زبون',customer_phone:'0591234567',issue_date:'2026-09-20',due_date:'2026-10-01',total,amount_paid:paid,status,created_at:'2026-09-20T10:00:00Z',...extra})
const rows=[row('1','paid',100.25,100.25),row('2','partial',200,50),row('3','sent',100,0),row('4','draft',500,0),row('5','cancelled',700,100)]
test('totals exclude drafts and cancelled, remaining includes partial invoices',()=>{const v=invoiceListView(rows,normalizeInvoiceFilters({}),'2026-10-02');assert.deepEqual(v.totals,{total:400.25,paid:150.25,remaining:250,drafts:1,activeCount:3,paidCount:1});assert.equal(v.counts.overdue,2);assert.equal(v.counts.unpaid,1);assert.equal(v.counts.partial,1)})
test('search, customer, month and status combine and totals follow visible scope',()=>{const v=invoiceListView(rows,normalizeInvoiceFilters({q:'059123',customer:'customer',month:'2026-09',status:'partial'}),'2026-10-02');assert.equal(v.filtered.length,1);assert.equal(v.totals.total,200);assert.equal(v.counts.all,5);assert.equal(invoiceListView(rows,normalizeInvoiceFilters({customer:'missing'}),'2026-10-02').filtered.length,0)})
test('date is overdue only after due date, excluding draft/cancelled; amounts determine settlement',()=>{assert.equal(invoiceOverdue(rows[1],'2026-10-01'),false);assert.equal(invoiceOverdue(rows[1],'2026-10-02'),true);assert.equal(invoiceOverdue(rows[3],'2026-10-02'),false);assert.equal(invoicePaymentKind(row('6','paid',100,0)),'unpaid');assert.equal(invoicePaymentKind(row('7','partial',100,100)),'paid')})
test('pagination clamps and date ordering is deterministic',()=>{const many=Array.from({length:15},(_,i)=>row(String(i).padStart(2,'0'),'paid',1,1));const v=invoiceListView(many,normalizeInvoiceFilters({size:'6',page:'99'}),'2026-10-02');assert.equal(v.page,3);assert.equal(v.visible.length,3);assert.deepEqual(v.visible.map(i=>i.id),['02','01','00']);assert.equal(normalizeInvoiceFilters({size:'999',month:'2026-99',status:'unknown'}).size,10)})
test('export contains real amounts and currency, including status and overdue',()=>{const result=invoiceExportRows([rows[1]],'ILS','2026-10-02')[0];assert.equal(result['المتبقي'],150);assert.equal(result['العملة'],'ILS');assert.equal(result['الحالة'],'مدفوعة جزئياً');assert.equal(result['متأخرة'],'نعم')})
