const fs=require('node:fs'),ts=require('typescript'),{test}=require('node:test'),assert=require('node:assert/strict');const cache={};function load(file){if(cache[file])return cache[file];const code=ts.transpileModule(fs.readFileSync(file+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,m={exports:{}};new Function('require','module','exports',code)(id=>load(require('node:path').resolve(require('node:path').dirname(file),id)),m,m.exports);return cache[file]=m.exports}const {paymentView,paymentNeedsReview,validateCashPayment}=load('lib/payments/presentation');
const payment={id:'p',voucher_number:'PMT-1',date:'2026-10-04',created_at:'2026-10-04T08:00:00Z',amount:100,cash_amount:100,checks_amount:0,payment_method:'cash',party_name:'Supplier',supplier_id:'s',description:'Payment',reference:'REF',cash_box_id:'b',purchase_invoice_id:'i',journal_entry_id:'j',postedJournalId:'j',actualCash:100,movementCount:1},filters={q:'',method:'all',supplier:'',from:'',to:'',page:1,size:10};
const suppliers=[{id:'s',name:'Supplier',phone:null,balance:50}],purchases=[{id:'i',supplier_id:'s',invoice_number:'PUR-1',invoice_date:'2026-10-02',total_amount:100,paid_amount:50,status:'completed',currency:'ILS',journal_entry_id:'j',postedJournalId:'j'}],boxes=[{id:'b',name:'Box',balance:200}],accounts=[{id:'expense'}],input={partyType:'supplier',supplierId:'s',partyName:'',date:'2026-10-04',amount:'50',boxId:'b',purchaseId:'i',description:'Payment',reference:'',debitAccountId:''};const validate=(p=input,inv=purchases,cash=boxes)=>validateCashPayment(p,suppliers,inv,cash,accounts,'ILS');
test('summary separates actual cash and nominal cheques',()=>{const v=paymentView([payment,{...payment,id:'c',amount:80,cash_amount:0,checks_amount:80,payment_method:'cheque',actualCash:0,movementCount:0}],filters);assert.equal(v.total,180);assert.equal(v.cash,100);assert.equal(v.cheques,80);assert.equal(v.review,0)});
test('filters and totals use the same result set with stable pagination',()=>{const rows=Array.from({length:12},(_,i)=>({...payment,id:String(i),supplier_id:i===0?'other':'s'}));let v=paymentView(rows,{...filters,supplier:'s',page:2});assert.equal(v.filtered.length,11);assert.equal(v.total,1100);assert.equal(v.rows.length,1);assert.equal(paymentView(rows,{...filters,q:'REF',method:'bank'}).total,0);assert.equal(paymentView(rows,{...filters,from:'2026-10-05',to:'2026-10-04'}).rows.length,0);assert.ok(paymentView(rows,{...filters,from:'2026-02-30'}).error)});
test('missing journal, duplicate movements, nonfinite or mismatched cash are flagged',()=>{assert.equal(paymentNeedsReview(payment),false);for(const p of [{postedJournalId:null},{movementCount:2},{actualCash:90},{amount:NaN},{amount:-1},{payment_method:'legacy-unknown'},{actualCheques:1,chequeCount:1},{checks_amount:10,actualCheques:0,chequeCount:0}])assert.equal(paymentNeedsReview({...payment,...p}),true)});
test('review enforces invoice ownership status journal currency dates and remaining cents',()=>{assert.equal(validate(),null);assert.equal(validate({...input,amount:'50.00'}),null);for(const p of [{amount:'50.01'},{date:'2026-10-01'},{supplierId:'unknown'},{purchaseId:'unknown'}])assert.ok(validate({...input,...p}));for(const p of [{supplier_id:'foreign'},{status:'draft'},{currency:'USD'},{postedJournalId:null},{paid_amount:NaN},{paid_amount:100},{hasReturns:true}])assert.ok(validate(input,[{...purchases[0],...p}]))});
test('review rejects unavailable cash and malformed amounts and dates',()=>{for(const p of [{amount:'0'},{amount:'1.001'},{amount:'Infinity'},{date:'2026-02-30'},{boxId:'foreign'},{description:''}])assert.ok(validate({...input,...p}));assert.ok(validate(input,purchases,[{...boxes[0],balance:NaN}]));assert.ok(validate(input,purchases,[{...boxes[0],balance:49.99}]))});
test('other party requires explicit account and has no supplier or invoice link',()=>{const p={...input,partyType:'other',supplierId:'',purchaseId:'',partyName:'Beneficiary',debitAccountId:'expense'};assert.equal(validate(p),null);for(const x of [{supplierId:'s'},{purchaseId:'i'},{partyName:''},{debitAccountId:'foreign'}])assert.ok(validate({...p,...x}))});
