const fs=require('node:fs'),ts=require('typescript'),{test}=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');const modules={};function load(name){if(modules[name])return modules[name];const code=ts.transpileModule(fs.readFileSync('lib/receipts/'+name+'.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,m={exports:{}};new Function('require','module','exports',code)(id=>id.startsWith('./')?load(id.slice(2)):require(id),m,m.exports);return modules[name]=m.exports}
const {inspectReceiptAttachment}=load('attachment-content'),{completeAttachmentUpload}=load('attachment-upload');
const pdf=Buffer.from('%PDF-1.4\nfixture\n%%EOF\n'),meta={name:'إثبات.pdf',type:'application/pdf',size:pdf.length};
test('content hash depends on bytes and validates PDF signature and ending',()=>{assert.equal(inspectReceiptAttachment(meta,pdf).sha256,createHash('sha256').update(pdf).digest('hex'));assert.throws(()=>inspectReceiptAttachment(meta,Buffer.alloc(pdf.length)),/محتوى/);assert.throws(()=>inspectReceiptAttachment({...meta,size:1},pdf),/حجم/);assert.throws(()=>inspectReceiptAttachment({...meta,name:'../proof.pdf'},pdf),/اسم/);assert.throws(()=>inspectReceiptAttachment({...meta,type:'text/html'},pdf),/المرفقات/)});
test('image signatures must match MIME and complete endings',()=>{const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0,73,69,78,68,174,66,96,130]);const jpg=Buffer.from([255,216,255,224,255,217]);const webp=Buffer.from('RIFFxxxxWEBP');webp.writeUInt32LE(4,4);for(const [type,b] of [['image/png',png],['image/jpeg',jpg],['image/webp',webp]]){assert.ok(inspectReceiptAttachment({...meta,type,size:b.length},b));assert.throws(()=>inspectReceiptAttachment({...meta,type,size:b.length-1},b.subarray(0,-1)),/محتوى/)}assert.throws(()=>inspectReceiptAttachment({...meta,type:'image/jpeg'},pdf),/محتوى/)});
const row={id:'id',status:'pending',sha256:createHash('sha256').update(pdf).digest('hex'),bytes:pdf.length,object_path:'path',content_type:'application/pdf'};
test('upload is verified before metadata becomes ready',async()=>{const calls=[];await completeAttachmentUpload(row,pdf,{put:async()=>calls.push('put'),read:async()=>{calls.push('read');return pdf},markReady:async()=>calls.push('ready')});assert.deepEqual(calls,['put','read','ready'])});
test('lost upload response and existing object can complete safely',async()=>{let ready=0;await completeAttachmentUpload(row,pdf,{put:async()=>{throw Error('timeout or duplicate')},read:async()=>pdf,markReady:async()=>{ready++}});assert.equal(ready,1)});
test('failed upload retains pending metadata and retries same object',async()=>{let ready=0;const io={put:async()=>{throw Error('network')},read:async()=>{throw Error('missing')},markReady:async()=>{ready++}};await assert.rejects(completeAttachmentUpload(row,pdf,io),/missing/);assert.equal(ready,0);await completeAttachmentUpload(row,pdf,{...io,read:async()=>pdf});assert.equal(ready,1)});
test('corrupted storage content is never marked ready',async()=>{let ready=0;await assert.rejects(completeAttachmentUpload(row,pdf,{put:async()=>{},read:async()=>Buffer.alloc(pdf.length),markReady:async()=>{ready++}}),/مطابقة/);assert.equal(ready,0)});
test('lost metadata response retries without rewriting uploaded object',async()=>{let writes=0;await assert.rejects(completeAttachmentUpload(row,pdf,{put:async()=>{writes++},read:async()=>pdf,markReady:async()=>{throw Error('db failure')}}),/db failure/);await completeAttachmentUpload(row,pdf,{put:async()=>{writes++;throw Error('duplicate')},read:async()=>pdf,markReady:async()=>{}});assert.equal(writes,2);let calls=0;await completeAttachmentUpload({...row,status:'ready'},pdf,{put:async()=>{calls++},read:async()=>{calls++;return pdf},markReady:async()=>{calls++}});assert.equal(calls,0)});
test('mismatched reselected file is rejected before storage write',async()=>{let calls=0;await assert.rejects(completeAttachmentUpload(row,Buffer.alloc(pdf.length),{put:async()=>{calls++},read:async()=>pdf,markReady:async()=>{calls++}}),/الحجز/);assert.equal(calls,0)});
