const fs=require('node:fs'),ts=require('typescript'),{test}=require('node:test'),assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const store='10000000-0000-0000-0000-000000000001',voucher='20000000-0000-0000-0000-000000000002',fileId='30000000-0000-0000-0000-000000000003',bytes=Buffer.from('%PDF-1.4\nfixture\n%%EOF\n');
function compile(file,imports){const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,m={exports:{}};new Function('require','module','exports',code)(id=>imports[id]||require(id),m,m.exports);return m.exports}
const pure={};function load(name){return pure[name]||(pure[name]=compile('lib/receipts/'+name+'.ts',new Proxy({},{get:(_,id)=>typeof id==='string'&&id.startsWith('./')?load(id.slice(2)):undefined})))}
function setup({user=true,activeStore=store,reserveError=null,readable=true}={}){const calls=[];const row={id:fileId,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length,status:'pending',content_type:'application/pdf',filename:'إثبات.pdf',object_path:store+'/'+voucher+'/hash'};const query={select(){return this},eq(){return this},order:async()=>({data:[],error:null}),maybeSingle:async()=>({data:readable?row:null,error:null}),single:async()=>({data:{id:fileId},error:null}),update(){calls.push('mark');return this}};const client={auth:{getUser:async()=>({data:{user:user?{id:'owner'}:null}})},rpc:async()=>{calls.push('reserve');return {data:reserveError?null:row,error:reserveError}},from:()=>query};const admin={storage:{from:()=>({upload:async()=>{calls.push('put');return {error:null}},download:async()=>{calls.push('download');return {data:new Blob([bytes]),error:null}}})},from:()=>query};const imports={'@/lib/supabase/server':{createClient:()=>client},'@/lib/supabase/admin':{createAdminClient:()=>{calls.push('admin');return admin}},'@/lib/supabase/getStore':{getStoreForUser:async()=>activeStore},'@/lib/receipts/attachment-content':load('attachment-content'),'@/lib/receipts/attachment-upload':load('attachment-upload'),'next/cache':{revalidatePath:()=>{}}};return {calls,action:compile('app/dashboard/accounting/receipts/attachment-actions.ts',imports),route:compile('app/dashboard/accounting/receipts/attachments/[id]/route.ts',imports)}}
const form={getAll:()=>[{name:'إثبات.pdf',type:'application/pdf',size:bytes.length,arrayBuffer:async()=>bytes}]};
test('unauthenticated and wrong-store upload never reach privileged storage',async()=>{for(const options of [{user:false},{activeStore:'foreign'}]){const s=setup(options);assert.equal((await s.action.uploadReceiptAttachment(store,voucher,form)).ok,false);assert.deepEqual(s.calls,[])}});
test('reserve rejection never invokes service-role client',async()=>{const s=setup({reserveError:{message:'permission denied'}});assert.equal((await s.action.uploadReceiptAttachment(store,voucher,form)).ok,false);assert.deepEqual(s.calls,['reserve'])});
test('valid file follows authorized reserve then verified upload and ready marker',async()=>{const s=setup();assert.equal((await s.action.uploadReceiptAttachment(store,voucher,form)).ok,true);assert.deepEqual(s.calls,['reserve','admin','put','download','mark'])});
test('download requires user-scoped RLS row before service download',async()=>{for(const options of [{user:false},{activeStore:null},{readable:false}]){const s=setup(options),res=await s.route.GET(new Request('http://localhost/'),{params:{id:fileId}});assert.ok([401,404].includes(res.status));assert.deepEqual(s.calls,[])}});
test('authorized download is private, uncached and forced as attachment',async()=>{const s=setup(),res=await s.route.GET(new Request('http://localhost/'),{params:{id:fileId}});assert.equal(res.status,200);assert.match(res.headers.get('cache-control'),/private.*no-store/);assert.equal(res.headers.get('x-content-type-options'),'nosniff');assert.match(res.headers.get('content-security-policy'),/sandbox/);assert.match(res.headers.get('content-disposition'),/^attachment;/);assert.deepEqual(Buffer.from(await res.arrayBuffer()),bytes)});
