import Link from 'next/link'
import CustomersTable from './CustomersTable'
import Icon,{type IconName} from '../simple/Icons'
import {directoryStats,type DirectoryCustomer} from '@/lib/customers/directory'
import styles from './directory.module.css'
export default function CustomerDirectory({customers,currencyCode,storeId,storeName='متجر بازاركو',countryCode='PS',date,lastOrderDates,loadError=false,orderError=false,preview=false,searchQuery='',activeType='all',sort='created_at',initShowAdd=false}:{customers:DirectoryCustomer[];currencyCode:string;storeId:string;storeName?:string;countryCode?:string;date:string;lastOrderDates:Record<string,string>;loadError?:boolean;orderError?:boolean;preview?:boolean;searchQuery?:string;activeType?:string;sort?:string;initShowAdd?:boolean}){
 const stats=directoryStats(customers,date)
 const overLimit=customers.filter(c=>c.is_active&&Number(c.credit_limit)>0&&Number(c.balance)>Number(c.credit_limit))
 const cards:{label:string;value:number;icon:IconName;sub?:string}[]=[{label:'إجمالي الزبائن',value:stats.total,icon:'users'},{label:'جديد هذا الشهر',value:stats.newThisMonth,icon:'plus'},{label:'زبائن لديهم رقم هاتف',value:stats.withPhone,icon:'share'},{label:'لديهم ذمة',value:stats.withDebt,icon:'wallet',sub:`${stats.totalDebt.toLocaleString('en-GB',{maximumFractionDigits:2})} ${currencyCode}`}]
 return <div className={styles.page} dir="rtl"><Link href="/dashboard/sales" className="text-sm text-slate-400">العودة إلى إدارة المبيعات ←</Link><header className={styles.heading}><h1>دليل وحسابات العملاء</h1><p>{loadError?'تعذر تحميل دليل وحسابات العملاء':`${customers.length} عميل مسجل · إدارة الزبائن، بيانات التواصل، الذمم وكشوف الحسابات في شاشة واحدة`}</p></header><div className={styles.stats}>{cards.map(c=><div key={c.label}><Icon name={c.icon}/><span>{c.label}</span><strong>{loadError?'—':c.value}</strong>{c.sub&&!loadError&&<small>{c.sub}</small>}</div>)}</div>{overLimit.length>0&&<details className="mb-5 rounded-xl border border-amber-500/30 bg-amber-500/5 p-4"><summary className="cursor-pointer text-amber-300">{overLimit.length} زبائن تجاوزوا حد الائتمان</summary><div className="mt-3 flex flex-wrap gap-3">{overLimit.map(c=><Link key={c.id} href={`/dashboard/customers/${c.id}`} className="text-sm text-slate-300">{c.name} · {c.balance} {currencyCode}</Link>)}</div></details>}{loadError&&<p role="alert" className={styles.error}>تعذر تحميل الزبائن. أعد تحميل الصفحة؛ المؤشرات غير متاحة حالياً.</p>}{orderError&&<p role="status" className={styles.error}>تعذر تحميل تواريخ آخر الطلبات. بقية بيانات الزبائن متاحة.</p>}<CustomersTable customers={customers} currencyCode={currencyCode} storeId={storeId} storeName={storeName} countryCode={countryCode} activeType={activeType} searchQuery={searchQuery} sort={sort} lastOrderDates={lastOrderDates} initShowAdd={initShowAdd} preview={preview} loadError={loadError} orderError={orderError}/></div>
}
