'use client'
import {useEffect,useRef,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
function Tag({size=24,strokeWidth=1.5,className=''}:{size?:number;strokeWidth?:number;className?:string}){return <svg aria-hidden="true" width={size} height={size} className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth}><path d="M3 12 12 3h8v8L11 20z"/><circle cx="16" cy="7" r="1.5"/></svg>}
function Box({size=24,className=''}:{size?:number;className?:string}){return <svg aria-hidden="true" width={size} height={size} className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10"/></svg>}
function Search({size=24,className=''}:{size?:number;className?:string}){return <svg aria-hidden="true" width={size} height={size} className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><circle cx="10" cy="10" r="7"/><path d="m15 15 7 7"/></svg>}
import {type Brand,brandSlug,validateBrand} from '@/lib/brands/presentation'
export default function BrandsClient({store,initialBrands,counts={},loadError=false,preview=false}:{store:{id:string;name:string;currency_code:string};initialBrands:Brand[];counts?:Record<string,number>;loadError?:boolean;preview?:boolean}){
 const router=useRouter(),lock=useRef(false);const [brands,setBrands]=useState(initialBrands),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[modal,setModal]=useState(false),[editing,setEditing]=useState<string|null>(null),[name,setName]=useState(''),[slug,setSlug]=useState(''),[description,setDescription]=useState(''),[active,setActive]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>setBrands(initialBrands),[initialBrands]);useEffect(()=>{if(!modal)return;function key(e:KeyboardEvent){if(e.key==='Escape'&&!lock.current)setModal(false)}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[modal])
 function open(b?:Brand){setEditing(b?.id||null);setName(b?.name||'');setSlug(b?.slug||'');setDescription(b?.description||'');setActive(b?.is_active??true);setError('');setModal(true)}
 async function save(e:React.FormEvent){e.preventDefault();if(lock.current)return;const invalid=validateBrand(name,slug);if(invalid){setError(invalid);return}if(preview){setError('معاينة فقط؛ لا تحفظ بيانات.');return}lock.current=true;setBusy(true);setError('');try{const c=createClient(),payload={name:name.trim(),slug,description:description.trim()||null,is_active:active};const result=editing?await c.from('brands').update(payload).eq('id',editing).eq('store_id',store.id).select('*').maybeSingle():await c.from('brands').insert({...payload,store_id:store.id}).select('*').single();if(result.error||!result.data)throw result.error||Error();setBrands(bs=>editing?bs.map(b=>b.id===editing?result.data:b):[...bs,result.data]);setModal(false);router.refresh()}catch(err:any){setError(err?.code==='23505'?'الرابط مستخدم لماركة أخرى؛ اختر رابطاً مختلفاً.':'تعذر حفظ الماركة. تحقق من القائمة قبل إعادة المحاولة إذا انقطع الاتصال.')}finally{lock.current=false;setBusy(false)}}
 const filtered=brands.filter(b=>(!status||(status==='active')===b.is_active)&&`${b.name} ${b.slug} ${b.description||''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>a.sort_order-b.sort_order||a.name.localeCompare(b.name,'ar'))
 return <main dir="rtl" className="text-slate-100 space-y-6"><header className="flex flex-wrap justify-between items-center gap-4"><div><p className="text-sm text-slate-400 mb-3">المخزون / الماركات</p><h1 className="text-3xl font-bold">الماركات</h1><p className="text-slate-400 mt-2">نظّم منتجاتك حسب الماركة وسهّل الوصول إليها.</p></div><Link href="/dashboard/inventory" className="rounded-xl border border-slate-700 px-5 py-3">العودة للمخزون ←</Link></header>
 {loadError?<p role="alert" className="rounded-xl bg-rose-950 p-5">تعذر تحميل الماركات أو عدد منتجاتها. أعد تحميل الصفحة.</p>:brands.length===0?<section className="rounded-2xl border border-slate-700 bg-[#0d1c32] p-6 sm:p-12 text-center"><div className="mx-auto w-36 h-36 rounded-full bg-sky-950 flex items-center justify-center text-sky-400"><Tag size={80} strokeWidth={1.2}/></div><h2 className="text-2xl font-bold mt-8">أضف أول ماركة لمشروعك</h2><p className="text-slate-400 mt-4">اربط منتجاتك بماركاتها لتسهيل العثور عليها.</p><button onClick={()=>open()} className="bg-sky-400 text-slate-950 rounded-xl px-7 py-4 font-bold mt-7">＋ إضافة أول ماركة</button><p className="text-sm text-slate-400 mt-4">لا توجد ماركات مضافة بعد.</p><div className="grid sm:grid-cols-3 gap-8 border-t border-slate-700 mt-10 pt-8">{[[Tag,'أضف الماركة','اكتب اسم الماركة.'],[Box,'اربط المنتجات','اختر الماركة عند إضافة المنتج.'],[Search,'سهّل البحث','اعثر على المنتجات حسب الماركة.']].map(([Icon,title,text]:any,i)=><div key={title}><span className="text-sky-300">{i+1}</span><Icon className="mx-auto my-4 text-sky-300" size={32}/><h3 className="font-bold">{title}</h3><p className="text-sm text-slate-400 mt-2">{text}</p></div>)}</div></section>:<><div className="flex flex-wrap gap-3"><input aria-label="بحث الماركات" placeholder="ابحث باسم الماركة أو رابطها..." value={query} onChange={e=>setQuery(e.target.value)} className="w-full sm:w-auto min-w-[200px] flex-1 bg-slate-900 border border-slate-700 rounded-xl p-3"/><select aria-label="حالة الماركة" value={status} onChange={e=>setStatus(e.target.value)} className="bg-slate-900 rounded-xl p-3"><option value="">جميع الحالات</option><option value="active">مفعلة</option><option value="inactive">غير مفعلة</option></select><button onClick={()=>open()} className="bg-sky-400 text-slate-950 rounded-xl px-5 py-3 font-bold">＋ إضافة ماركة</button></div><p className="text-sm text-slate-400">{filtered.length} من {brands.length} ماركة</p><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-4">{filtered.map(b=><article key={b.id} className="rounded-2xl border border-slate-700 bg-[#0d1c32] p-6"><Tag className="text-sky-400"/><h2 className="text-xl font-bold mt-4 break-words">{b.name}</h2><p className="text-xs text-slate-400 mt-2 break-all" dir="ltr">{b.slug}</p><p className="text-sm text-slate-400 my-4 break-words">{b.description}</p><p className={b.is_active?'text-emerald-400':'text-amber-400'}>{b.is_active?'مفعلة':'غير مفعلة'} · {counts[b.id]||0} منتج</p><div className="flex flex-wrap gap-4 mt-5"><Link className="text-sky-300" href={`/dashboard/products?brand_id=${encodeURIComponent(b.id)}`}>عرض المنتجات ←</Link>{b.is_active&&<Link className="text-sky-300" href={`/dashboard/products/new?brand_id=${encodeURIComponent(b.id)}`}>ربط منتج جديد</Link>}<button onClick={()=>open(b)} className="text-slate-300">تعديل</button></div></article>)}</div>{!filtered.length&&<p className="p-10 text-center text-slate-400">لا توجد ماركات تطابق البحث.</p>}</>}
 {modal&&<div className="fixed inset-0 z-50 bg-black/80 p-4 flex items-center justify-center"><section role="dialog" onKeyDown={e=>{if(e.key!=='Tab')return;const els=e.currentTarget.querySelectorAll<HTMLElement>('input,textarea,button:not(:disabled)');const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}} aria-modal="true" aria-labelledby="brand-title" className="w-full max-w-lg max-h-[90vh] overflow-auto bg-slate-900 border border-slate-700 rounded-2xl p-6"><h2 id="brand-title" className="text-xl font-bold">{editing?'تعديل الماركة':'إضافة ماركة'}</h2><form onSubmit={save} className="space-y-4 mt-5"><label className="block">اسم الماركة<input autoFocus required maxLength={100} value={name} onChange={e=>{setName(e.target.value);if(!editing)setSlug(brandSlug(e.target.value))}} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="block">الرابط الفرعي<input required maxLength={40} dir="ltr" value={slug} onChange={e=>setSlug(e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="block">الوصف<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="flex gap-3"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>ماركة مفعلة</label><p className="text-xs text-slate-400">تعطيل الماركة يحفظ روابط المنتجات الحالية؛ لا يغيّر ظهور المنتجات.</p>{error&&<p role="alert" className="text-rose-400">{error}</p>}<div className="flex gap-3"><button disabled={busy} className="bg-sky-400 text-slate-950 rounded-xl p-3 flex-1 font-bold">{busy?'جارٍ الحفظ...':'حفظ الماركة'}</button><button type="button" disabled={busy} onClick={()=>setModal(false)} className="border border-slate-700 rounded-xl p-3 flex-1">إلغاء</button></div></form></section></div>}
 </main>
}
