export interface StockMovement {id:string;movement_date:string;created_at:string;movement_type:string;document_number:string|null;document_type:string|null;ref_id:string|null;entity_name:string|null;quantity_in:number;quantity_out:number;balance_after:number|null;unit_price?:number|null}
export interface StatementProduct {id:string;name:string;sku:string|null;barcode:string|null;stock_quantity:number;price:number;cost_price?:number|null;thumbnail_url?:string|null;track_stock:boolean}
export const movementLabels:Record<string,string>={sale:'فاتورة مبيعات',purchase:'فاتورة مشتريات',sales_return:'مرتجع مبيعات',purchase_return:'مردود مشتريات',adjustment_in:'تسوية زيادة',adjustment_out:'تسوية نقص',transfer_in:'تحويل وارد',transfer_out:'تحويل صادر',damage:'تالف',initial:'رصيد افتتاحي'}
const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100
export function validStatementDate(s:string){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s}
export function stockStatement(movements:StockMovement[],current:number,filters:{from?:string;to?:string;type?:string;q?:string;page?:number;size?:number}){
 const from=filters.from||'',to=filters.to||'';if((from&&!validStatementDate(from))||(to&&!validStatementDate(to))||(from&&to&&from>to))return {error:'اختر فترة صحيحة؛ تاريخ البداية لا يتجاوز النهاية.'} as const
 const byCreated=[...movements].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));const anchor=byCreated[0];const delta=(m:StockMovement)=>Number(m.quantity_in||0)-Number(m.quantity_out||0)
 const anchored=!!anchor&&byCreated.filter(m=>m.created_at===anchor.created_at).length===1&&anchor.balance_after!==null&&Number.isFinite(Number(anchor.balance_after));const base=anchored?round(Number(anchor.balance_after)-delta(anchor)):round(current-movements.reduce((s,m)=>s+delta(m),0))
 let running=base;const all=[...movements].sort((a,b)=>a.movement_date.localeCompare(b.movement_date)||a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id)).map(m=>({...m,computed_balance:running=round(running+delta(m))}))
 const before=all.filter(m=>from&&m.movement_date<from);const opening=before.length?before[before.length-1].computed_balance:base
 const period=all.filter(m=>(!from||m.movement_date>=from)&&(!to||m.movement_date<=to));const totalIn=round(period.reduce((s,m)=>s+Number(m.quantity_in||0),0)),totalOut=round(period.reduce((s,m)=>s+Number(m.quantity_out||0),0)),closing=round(opening+totalIn-totalOut)
 const q=(filters.q||'').trim().toLowerCase();const filtered=period.filter(m=>(!filters.type||m.movement_type===filters.type)&&(!q||`${m.document_number||''} ${m.entity_name||''} ${movementLabels[m.movement_type]||m.movement_type}`.toLowerCase().includes(q)))
 const size=[7,10,25,50].includes(Number(filters.size))?Number(filters.size):7;const pages=Math.max(1,Math.ceil(filtered.length/size)),page=Math.max(1,Math.min(pages,Math.floor(Number(filters.page))||1));const latest=all.length?all[all.length-1].computed_balance:base
 return {error:null,opening,totalIn,totalOut,closing,base,anchored,latest,reconciled:anchored?Math.abs(latest-current)<.005:null,period,filtered,visible:filtered.slice((page-1)*size,page*size),page,pages,size}
}
export function movementLink(m:StockMovement){if(!m.ref_id||!/^[-a-zA-Z0-9]+$/.test(m.ref_id))return null;if(m.document_type==='invoice')return `/dashboard/accounting/invoices/${m.ref_id}`;if(['فاتورة مشتريات','فاتورة مشتريات (أمر شراء)'].includes(m.document_type||''))return `/dashboard/purchases/print/${m.ref_id}`;if(['مرتجع مبيعات','مرتجع مبيعات (معدل)'].includes(m.document_type||''))return `/dashboard/invoices/returns/print/${m.ref_id}`;if(m.document_type==='مردودات مشتريات')return `/dashboard/purchases/returns/print/${m.ref_id}`;if(m.document_type==='order')return `/dashboard/orders/${m.ref_id}`;return null}
