'use client'
import {useState,useEffect,useRef} from 'react'
import Link from 'next/link'
import ReceiptAttachments from './ReceiptAttachments'
import {useRouter} from 'next/navigation'
import {createBankReceipt} from '@/app/dashboard/accounting/receipts/receipt-action'
import {businessDay} from '@/lib/dashboard/simple-metrics'
import {type ReceiptCustomer,type ReceiptInvoice} from '@/lib/receipts/presentation'
import {validateBankReview,validateReceiptFiles,type BankReview,type ReceiptBank} from '@/lib/receipts/bank-review'
import s from '@/components/dashboard/accounting/invoices-list.module.css'
export default function BankReceiptReview({banks,customers,invoices,creditAccounts,currency,storeId,preview,onBusyChange}:{storeId:string;preview:boolean;onBusyChange:(busy:boolean)=>void;banks:ReceiptBank[];customers:ReceiptCustomer[];invoices:ReceiptInvoice[];creditAccounts:{id:string;name:string;code:string}[];currency:string}){
 const [input,setInput]=useState<BankReview>({partyType:'customer',customerId:'',partyName:'',date:businessDay().date,amount:'',bankId:'',invoiceId:'',description:'',reference:'',creditAccountId:''}),[files,setFiles]=useState<File[]>([]),[review,setReview]=useState(false),[error,setError]=useState('');
 const router=useRouter(),pending=useRef<{id:string;input:BankReview;fileNames?:string[]}|null>(null),flight=useRef(false);
 const [saving,setSaving]=useState(false),[uncertain,setUncertain]=useState(false),[saved,setSaved]=useState<{id:string;number:string}|null>(null);
 useEffect(()=>{onBusyChange(saving||uncertain)},[saving,uncertain,onBusyChange]);
 useEffect(()=>{if(preview||!storeId)return;try{const raw=sessionStorage.getItem(`bank-receipt-pending:${storeId}`);if(!raw)return;const p=JSON.parse(raw);if(!/^[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}$/i.test(p.id)||!p.input||!['partyType','customerId','partyName','date','amount','bankId','invoiceId','description','reference','creditAccountId'].every(k=>typeof p.input[k]==='string'))throw Error();pending.current=p;setInput(p.input);setUncertain(true);setReview(true);setError('طلب سابق غير مؤكد؛ أعد محاولة الطلب نفسه قبل إدخال سند آخر. إذا كنت اخترت مرفقات، أعد اختيارها بعد تأكيد السند')}catch{setUncertain(true);setError('تعذر قراءة طلب القبض السابق؛ تحقق من نتيجته قبل تسجيل سند آخر')}},[storeId,preview]);
 async function save(){if(flight.current||preview||!storeId)return;if(!pending.current){const message=validateBankReview(input,files,customers,invoices,banks,creditAccounts,currency);if(message){setError(message);setReview(false);return}pending.current={id:crypto.randomUUID(),input:{...input},fileNames:files.map(f=>f.name)}}flight.current=true;setSaving(true);setError('');
 try{try{sessionStorage.setItem(`bank-receipt-pending:${storeId}`,JSON.stringify(pending.current))}catch{setError('تعذر حفظ معرف الطلب في المتصفح؛ لم يُرسل السند');return}
 const result=await createBankReceipt(storeId,pending.current.id,pending.current.input);
 if(result.ok&&result.voucherId){setSaved({id:result.voucherId,number:result.voucherNumber||''});setUncertain(false);setReview(false);pending.current=null;try{sessionStorage.removeItem(`bank-receipt-pending:${storeId}`)}catch{}router.refresh()}
 else{setError(result.error||'تعذر الحفظ');setUncertain(uncertain||!!result.uncertain);if(!uncertain&&!result.uncertain){pending.current=null;try{sessionStorage.removeItem(`bank-receipt-pending:${storeId}`)}catch{}setReview(false);router.refresh()}}
 }catch{setUncertain(true);setError('تعذر تأكيد نتيجة الحفظ؛ أعد محاولة الطلب نفسه')}finally{flight.current=false;setSaving(false)}}
 const field='block w-full rounded-xl p-3 mt-2 bg-slate-800 border border-slate-700',bank=banks.find(b=>b.id===input.bankId),customer=customers.find(c=>c.id===input.customerId),invoice=invoices.find(i=>i.id===input.invoiceId),money=(n:number)=>`${Number.isFinite(n)?n.toFixed(2):'—'} ${currency}`;
 function change(p:Partial<BankReview>){if(saving||uncertain||saved)return;pending.current=null;if(Object.entries(p).every(([k,v])=>input[k as keyof BankReview]===v))return;setInput(v=>({...v,...p}));setReview(false);setError('')}
 return <section className={`${s.panel} mt-5`} dir="rtl"><h2 className="text-2xl font-bold">سند قبض بنكي</h2><p className={s.notice}>راجع التحويل قبل الاعتماد. يحفظ السند والبنك والقيد والعميل والفاتورة معاً. يُحفظ السند أولاً، ثم ترفع المرفقات الخاصة في خطوة مستقلة. فشل الرفع لا يلغي السند ولا يكرر القبض.</p><div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)] gap-6"><form className="space-y-5 min-w-0" onSubmit={e=>{e.preventDefault();const message=validateBankReview(input,files,customers,invoices,banks,creditAccounts,currency);setError(message||'');setReview(!message)}}><fieldset disabled={saving||uncertain||!!saved} className="space-y-5 min-w-0"><div className="grid sm:grid-cols-2 gap-4"><label>تاريخ القبض<input aria-label="تاريخ القبض البنكي" type="date" value={input.date} className={field} onChange={e=>change({date:e.target.value})} onBlur={e=>change({date:e.target.value})}/></label><label>مبلغ التحويل<input aria-label="مبلغ القبض البنكي" inputMode="decimal" className={field} value={input.amount} onChange={e=>change({amount:e.target.value})}/></label></div><label className="block">نوع الجهة<select aria-label="نوع جهة القبض البنكي" className={field} value={input.partyType} onChange={e=>change({partyType:e.target.value as 'customer'|'other',customerId:'',partyName:'',invoiceId:'',creditAccountId:''})}><option value="customer">عميل مسجل</option><option value="other">جهة أخرى</option></select></label>
 {input.partyType==='customer'?<label className="block">العميل<select aria-label="عميل القبض البنكي" className={field} value={input.customerId} onChange={e=>change({customerId:e.target.value,invoiceId:''})}><option value="">اختر العميل</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} {c.phone}</option>)}</select></label>:<><label className="block">اسم الجهة<input aria-label="اسم جهة القبض البنكي" className={field} maxLength={200} value={input.partyName} onChange={e=>change({partyName:e.target.value})}/></label><label className="block">الحساب المقابل<select aria-label="حساب القبض البنكي المقابل" className={field} value={input.creditAccountId} onChange={e=>change({creditAccountId:e.target.value})}><option value="">اختر الحساب</option>{creditAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label></>}
 <label className="block">الحساب البنكي المستلم<select aria-label="حساب القبض البنكي" className={field} value={input.bankId} onChange={e=>change({bankId:e.target.value})}><option value="">اختر حساباً بعملة {currency}</option>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} — {b.account_number}</option>)}</select></label>{!banks.length&&<p className="text-amber-300">لا يوجد حساب بنكي نشط بحساب محاسبي مطابق وصلاحية مناسبة. راجع إعدادات البنك.</p>}
 {input.partyType==='customer'&&<label className="block">ربط فاتورة (اختياري)<select aria-label="فاتورة القبض البنكي" className={field} value={input.invoiceId} onChange={e=>change({invoiceId:e.target.value})}><option value="">على حساب العميل دون فاتورة</option>{invoices.filter(i=>i.customer_id===input.customerId&&!['draft','cancelled'].includes(i.status)&&Number(i.total)>Number(i.amount_paid)).map(i=><option key={i.id} value={i.id}>{i.invoice_number} · متبقٍ {money(Number(i.total)-Number(i.amount_paid))}</option>)}</select></label>}
 <label className="block">مرجع التحويل البنكي<input aria-label="مرجع القبض البنكي" maxLength={200} className={field} value={input.reference} onChange={e=>change({reference:e.target.value})}/></label><label className="block">البيان<textarea aria-label="بيان القبض البنكي" maxLength={1000} rows={3} className={field} value={input.description} onChange={e=>change({description:e.target.value})}/></label>
 <section className="border border-slate-700 rounded-xl p-4 space-y-3"><h3 className="font-bold">اختيار مرفقات التحويل</h3><p className={s.hint}>PDF، JPG، PNG، WebP · خمسة ملفات كحد أقصى · 5 ميغابايت للملف و15 ميغابايت إجمالاً. تُرفع الملفات بعد حفظ السند من قسم المرفقات الخاصة. اختيار الملفات وحده لا يرفعها. عند إغلاق الصفحة أعد اختيار الملفات لاستكمال الرفع.</p><input aria-label="مرفقات القبض البنكي" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" multiple className="max-w-full" onChange={e=>{const selected=Array.from(e.target.files||[]),next=[...files,...selected],message=validateReceiptFiles(next);setReview(false);setError(message||'');if(!message)setFiles(next);e.target.value=''}}/>{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex justify-between gap-3 min-w-0"><span className="break-all">{f.name} · {(f.size/1024).toFixed(1)} KB</span><button type="button" aria-label={`إزالة المرفق ${i+1}`} onClick={()=>{setFiles(v=>v.filter((_,n)=>n!==i));setReview(false);setError('')}}>إزالة</button></div>)}</section>{error&&<p role="alert" className={s.error}>{error}</p>}<button type="submit" className={s.primary}>مراجعة القبض البنكي</button></fieldset></form>
 <aside className="min-w-0 self-start bg-slate-900 border border-slate-700 rounded-xl p-5 space-y-4"><h3 className="text-xl font-bold">ملخص التحويل</h3><strong className="text-3xl text-sky-300 block">{money(Number(input.amount||0))}</strong><p>المستلم منه: {input.partyType==='customer'?customer?.name||'لم يُحدد':input.partyName||'لم يُحدد'}</p><p>البنك: {bank?`${bank.bank_name} — ${bank.account_number}`:'لم يُحدد'}</p><p>الفاتورة: {invoice?.invoice_number||'دون ربط'}</p><p>المرجع: {input.reference||'لم يُحدد'}</p><p>المرفقات المختارة: {files.length} · {saved?'راجع حالة المرفقات في القسم التالي':'لم تُرفع'}</p><p className={s.notice}>التحويل البنكي لا ينشئ حركة صندوق نقدي. القبض دون فاتورة قد ينشئ رصيداً دائناً للعميل.</p>{review&&!saving&&!uncertain&&!saved&&<p role="status" className={s.settled}>اجتاز التحويل المراجعة. لم يُحفظ سند ولم تُرفع ملفات ولم تتغير أرصدة.</p>}{error&&(saving||uncertain||saved)&&<p role="alert" className={s.error}>{error}</p>}{saved&&<p role="status" className={s.settled}>حُفظ السند {saved.number}. <Link href={`/dashboard/accounting/receipts/print/${saved.id}`}>عرض / طباعة</Link></p>}{files.length>0&&!saved&&<p className="text-amber-300">حفظ السند لا يرفع الملفات؛ استكمل رفعها بعد الحفظ.</p>}<button type="button" onClick={save} disabled={preview||saving||!!saved||(!review&&!uncertain)||(!pending.current&&uncertain)} className="w-full rounded-xl p-3 bg-sky-500 font-bold disabled:opacity-40">{preview?'معاينة فقط — لا حفظ مالي':saving?'جارٍ حفظ السند…':uncertain?'إعادة محاولة الطلب نفسه':files.length?'حفظ السند ثم استكمال المرفقات':'اعتماد سند القبض البنكي'}</button></aside></div>{saved&&<div className="mt-5"><ReceiptAttachments storeId={storeId} voucherId={saved.id} initialFiles={files} onBusyChange={onBusyChange}/></div>}</section>
}
