'use client'
import {useState,useRef,useEffect} from 'react'
import {useRouter} from 'next/navigation'
import {createCashReceipt} from '@/app/dashboard/accounting/receipts/receipt-action'
import Link from 'next/link'
import ChequeReceiptReview from './ChequeReceiptReview'
import {businessDay} from '@/lib/dashboard/simple-metrics'
import {declaredCash,receiptView,receiptMethods,receiptMethod,receiptNeedsReview,validateCashReview,type Receipt,type ReceiptCustomer,type ReceiptInvoice,type CashReview} from '@/lib/receipts/presentation'
import s from '@/components/dashboard/accounting/invoices-list.module.css'
export default function Receipts({receipts,customers,invoices,cashBoxes,creditAccounts,currency,portfolios=[],storeId='',preview=false,initialCustomer=''}:{portfolios?:{id:string;name:string}[];storeId?:string;preview?:boolean;initialCustomer?:string;receipts:Receipt[];customers:ReceiptCustomer[];invoices:ReceiptInvoice[];cashBoxes:{id:string;name:string}[];creditAccounts:{id:string;name:string;code:string}[];currency:string}){
 const [chequeOpen,setChequeOpen]=useState(false),[chequeBusy,setChequeBusy]=useState(false),[ready,setReady]=useState(preview);
 useEffect(()=>{if(preview)return;try{if(sessionStorage.getItem(`cheque-receipt-pending:${storeId}`)){setChequeOpen(true);setOpen(false);setChequeBusy(true)}}catch{setChequeOpen(true);setOpen(false);setChequeBusy(true)}finally{setReady(true)}},[storeId,preview]);
 const [q,setQ]=useState(''),[method,setMethod]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[open,setOpen]=useState(!!initialCustomer),[customerQuery,setCustomerQuery]=useState(''),[message,setMessage]=useState(''),[review,setReview]=useState(false),[form,setForm]=useState<CashReview>({partyType:'customer',customerId:initialCustomer,partyName:'',date:businessDay().date,amount:'',boxId:'',invoiceId:'',description:'',reference:'',creditAccountId:''});
 const router=useRouter(),pending=useRef<{id:string;input:CashReview}|null>(null),inFlight=useRef(false);
 const [saving,setSaving]=useState(false),[uncertain,setUncertain]=useState(false),[saved,setSaved]=useState<{id:string;number:string}|null>(null);
 useEffect(()=>{if(preview||!storeId)return;try{const raw=sessionStorage.getItem(`cash-receipt-pending:${storeId}`);if(!raw)return;const p=JSON.parse(raw);if(!/^[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}$/i.test(p.id)||!p.input||!['partyType','customerId','partyName','date','amount','boxId','invoiceId','description','reference','creditAccountId'].every(k=>typeof p.input[k]==='string'))throw Error('invalid pending');pending.current=p;setForm(p.input);setOpen(true);setUncertain(true);setReview(true);setMessage('يوجد طلب سابق لم تتأكد نتيجته؛ أعد محاولة الطلب نفسه قبل إدخال سند آخر')}catch{setMessage('تعذر قراءة طلب القبض السابق؛ تحقق من النتيجة قبل تسجيل سند آخر');setUncertain(true);setOpen(true)}},[storeId,preview]);
 async function save(){if(inFlight.current||preview||!storeId)return;if(!pending.current){const error=validateCashReview(form,customers,invoices,cashBoxes,creditAccounts);if(error){setMessage(error);setReview(false);return}pending.current={id:crypto.randomUUID(),input:{...form}}}inFlight.current=true;setSaving(true);setMessage('');
 try{try{sessionStorage.setItem(`cash-receipt-pending:${storeId}`,JSON.stringify(pending.current))}catch{setMessage('تعذر حفظ معرف الطلب في المتصفح؛ لم يُرسل السند. فعّل التخزين ثم أعد المحاولة');return}
 const result=await createCashReceipt(storeId,pending.current.id,pending.current.input);
 if(result.ok&&result.voucherId){setSaved({id:result.voucherId,number:result.voucherNumber||''});setUncertain(false);setReview(false);pending.current=null;try{sessionStorage.removeItem(`cash-receipt-pending:${storeId}`)}catch{}router.refresh()}
 else{setMessage(result.error||'تعذر الحفظ');setUncertain(uncertain||!!result.uncertain);if(!uncertain&&!result.uncertain){pending.current=null;try{sessionStorage.removeItem(`cash-receipt-pending:${storeId}`)}catch{}setReview(false);router.refresh()}}
 }catch{setUncertain(true);setMessage('تعذر تأكيد نتيجة الحفظ؛ أعد محاولة الطلب نفسه')}finally{inFlight.current=false;setSaving(false)}}
 const view=receiptView(receipts,q,method,from,to,page,size),customer=customers.find(c=>c.id===form.customerId),invoice=invoices.find(i=>i.id===form.invoiceId),box=cashBoxes.find(b=>b.id===form.boxId),account=creditAccounts.find(a=>a.id===form.creditAccountId),money=(n:number)=>`${n.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`;
 function change<K extends keyof CashReview>(field:K,value:CashReview[K]){if(saving||uncertain||saved)return;pending.current=null;setForm({...form,[field]:value,...(field==='customerId'||field==='partyType'?{invoiceId:''}:{}),...(field==='partyType'?{customerId:'',partyName:'',creditAccountId:''}:{})});setReview(false);setMessage('')}
 return <main className={s.page} dir="rtl"><Link href="/dashboard/accounting-hub" className={s.back}>← الإدارة المالية والمحاسبية</Link><header className={s.header}><div><h1>سندات القبض</h1><p>المبالغ المسجلة ووسائل القبض وروابط المستندات</p></div><div className={s.buttons}><button className={s.primary} disabled={!ready||saving||uncertain||chequeBusy} onClick={()=>{if(saved)setForm({...form,amount:'',invoiceId:'',description:'',reference:'',date:businessDay().date});setSaved(null);setChequeOpen(false);setOpen(true);setReview(false);setMessage('')}}>＋ سند قبض نقدي جديد</button><button disabled={!ready||saving||uncertain||chequeBusy} onClick={()=>{setOpen(false);setChequeOpen(!chequeOpen)}}>{chequeOpen?'إغلاق مراجعة الشيكات':'＋ قبض شيكات / مختلط'}</button></div></header><p className={s.notice}>يحفظ القبض النقدي والسند وحركة الصندوق والقيد وذمة العميل وتحصيل الفاتورة معاً. يحفظ قبض الشيكات والمختلط ذرياً؛ قيمة الشيك اسمية ولا تزيد النقد. التحصيل والإعادة من محفظة الشيكات، مع ربط تسوية العميل والفاتورة. التحويل البنكي في المرحلة 22.</p>
 <section className={s.stats}>{[['إجمالي السندات',money(view.total)],['عدد السندات',String(view.filtered.length)],['قبض نقدي مسجل بالصناديق',money(view.cash)],['شيكات اسمية في السندات',money(view.cheques)]].map(([label,value])=><article key={label} className={s.stat}><div><span>{label}</span><strong>{view.error?'—':value}</strong><small>حسب الفلاتر · الشيكات لا تعني تحصيلاً نقدياً</small></div></article>)}</section>
 <section className={s.panel}><div className={s.filters}><input aria-label="بحث سندات القبض" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}} placeholder="رقم السند أو المستلم منه أو البيان أو المرجع…"/><label>من تاريخ<input aria-label="بداية فترة السندات" type="date" value={from} onBlur={e=>{setFrom(e.target.value);setPage(1)}} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>إلى تاريخ<input aria-label="نهاية فترة السندات" type="date" value={to} onBlur={e=>{setTo(e.target.value);setPage(1)}} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label><button onClick={()=>{setQ('');setMethod('all');setFrom('');setTo('');setPage(1)}}>مسح الفلاتر</button></div><div className={s.tabs}>{[['all','الكل'],...Object.entries(receiptMethods)].map(([value,label])=><button key={value} aria-pressed={method===value} onClick={()=>{setMethod(value);setPage(1)}}>{label}</button>)}</div></section>
 {view.error?<p role="alert" className={s.error}>{view.error}</p>:<>{view.review>0&&<p className={s.notice}>{view.review} سند يحتاج مراجعة ربط القيد أو مطابقة الحركة النقدية. لا تُغيّر الأرصدة تلقائياً.</p>}<div className={s.tableWrap}><table><thead><tr>{['رقم السند','التاريخ','المستلم منه','طريقة القبض','البيان','المبلغ','القيد والمطابقة','المستندات'].map(t=><th key={t}>{t}</th>)}</tr></thead><tbody>{view.rows.map(v=><tr key={v.id}><td className={s.number}>{v.voucher_number}</td><td>{v.date}</td><td>{v.party_name||'غير مسجل'}{v.supplier_id&&<small>مورد · {v.purchase_return_id?'استرداد مرتبط بمرتجع':'راجع مصدر القبض'}</small>}</td><td><span className={`${s.badge} ${receiptMethod(v.payment_method)==='cash'?s.paid:s.partial}`}>{receiptMethods[receiptMethod(v.payment_method)]}</span>{v.chequeCount>0&&<small>{v.chequeCount} شيك مرتبط · القيمة اسمية</small>}</td><td>{v.description||'—'}{v.reference&&<small>{v.reference}</small>}</td><td>{money(Number(v.amount))}</td><td>{receiptNeedsReview(v)?<span className="text-amber-300">يحتاج مراجعة</span>:<span className="text-emerald-300">{declaredCash(v)>0?'قيد مرحّل · النقد مطابق':'قيد مرحّل · سند غير نقدي'}</span>}</td><td><div className={s.rowActions}><Link href={`/dashboard/accounting/receipts/print/${v.id}`}>عرض / طباعة</Link>{v.postedJournalId&&<Link href={`/dashboard/accounting/journal/print/${v.postedJournalId}`}>القيد</Link>}{v.invoice_id&&<Link href={`/dashboard/accounting/invoices/${v.invoice_id}`}>الفاتورة</Link>}{v.purchase_return_id&&<Link href={`/dashboard/purchases/returns/print/${v.purchase_return_id}`}>المرتجع</Link>}</div></td></tr>)}{!view.rows.length&&<tr><td colSpan={8} className={s.empty}>{receipts.length?'لا توجد سندات تطابق الفلاتر':'لا توجد سندات قبض مسجلة'}</td></tr>}</tbody></table></div><div className={s.pagination}><label>لكل صفحة <select aria-label="عدد السندات في الصفحة" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select></label><span>الصفحة {view.page} من {view.pages} · {view.filtered.length} سند</span><div><button disabled={view.page===1} onClick={()=>setPage(view.page-1)}>السابق</button><button disabled={view.page===view.pages} onClick={()=>setPage(view.page+1)}>التالي</button></div></div></>}
 {saved&&<p role="status" className={s.notice}>حُفظ سند القبض {saved.number} وجميع آثاره المالية. <Link href={`/dashboard/accounting/receipts/print/${saved.id}`}>عرض السند / الطباعة</Link></p>}
 {uncertain&&<p role="alert" className={s.notice}>{message||'نتيجة الحفظ غير مؤكدة؛ أعد محاولة الطلب نفسه. لا تنشئ سنداً بديلاً.'}</p>}
 {chequeOpen&&<ChequeReceiptReview storeId={storeId} preview={preview} onBusyChange={setChequeBusy} customers={customers} invoices={invoices} cashBoxes={cashBoxes} portfolios={portfolios} creditAccounts={creditAccounts} currency={currency}/>}
 {open&&!chequeBusy&&ready&&<section className={`${s.panel} mt-5`}><div className="flex justify-between gap-4"><h2 className="text-2xl font-bold">سند قبض نقدي جديد</h2><button aria-label="إغلاق نموذج القبض" disabled={saving||uncertain} onClick={()=>setOpen(false)}>×</button></div><p className={s.hint}>راجع البيانات قبل الاعتماد. المراجعة وحدها لا تنشئ حركة مالية.</p><div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)] gap-6 mt-5"><form onSubmit={e=>{e.preventDefault();const error=validateCashReview(form,customers,invoices,cashBoxes,creditAccounts);setMessage(error||'');setReview(!error)}} className="space-y-5 min-w-0"><fieldset disabled={saving||uncertain||!!saved} className="space-y-5 min-w-0"><div className="flex gap-3 flex-wrap"><button type="button" aria-pressed={form.partyType==='customer'} onClick={()=>change('partyType','customer')} className={form.partyType==='customer'?s.primary:''}>عميل مسجل</button><button type="button" aria-pressed={form.partyType==='other'} onClick={()=>change('partyType','other')} className={form.partyType==='other'?s.primary:''}>جهة أخرى</button><span className="text-emerald-300">طريقة القبض: نقدي</span></div><div className="grid sm:grid-cols-2 gap-4"><label>تاريخ السند *<input aria-label="تاريخ سند القبض" type="date" value={form.date} onBlur={e=>change('date',e.target.value)} onChange={e=>change('date',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label>المبلغ النقدي *<input aria-label="مبلغ القبض النقدي" inputMode="decimal" value={form.amount} onChange={e=>change('amount',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2" placeholder={`0.00 ${currency}`}/></label></div>
 {form.partyType==='customer'?<section><label>بحث العميل<input aria-label="بحث عميل القبض" value={customerQuery} onChange={e=>setCustomerQuery(e.target.value)} placeholder="اسم أو هاتف…" className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="block mt-3">العميل المستلم منه *<select aria-label="عميل القبض" value={form.customerId} onChange={e=>change('customerId',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"><option value="">اختر العميل</option>{customers.filter(c=>c.id===form.customerId||`${c.name} ${c.phone||''}`.toLowerCase().includes(customerQuery.trim().toLowerCase())).map(c=><option value={c.id} key={c.id}>{c.name} {c.phone||''}</option>)}</select></label></section>:<><label className="block">اسم الجهة المستلم منها *<input aria-label="اسم جهة القبض" maxLength={200} value={form.partyName} onChange={e=>change('partyName',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="block">الحساب المقابل *<select aria-label="حساب القبض المقابل" value={form.creditAccountId} onChange={e=>change('creditAccountId',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"><option value="">اختر حساب إيراد أو التزام أو حقوق ملكية</option>{creditAccounts.map(a=><option value={a.id} key={a.id}>{a.code} — {a.name}</option>)}</select></label><p className={s.hint}>القبض من جهة أخرى لا يُصنّف تلقائياً كمبيعات؛ اختيار الحساب يحتاج مراجعة المحاسب.</p></>}
 <label className="block">الصندوق المستهدف *<select aria-label="صندوق القبض النقدي" value={form.boxId} onChange={e=>change('boxId',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"><option value="">اختر صندوقاً مصرحاً به</option>{cashBoxes.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label>{!cashBoxes.length&&<p className="text-amber-300">لا يوجد صندوق نقدي نشط ذو حساب مطابق وصلاحية قبض. راجع إعدادات الخزينة.</p>}
 {form.partyType==='customer'&&<label className="block">ربط فاتورة (اختياري)<select aria-label="فاتورة القبض" value={form.invoiceId} onChange={e=>change('invoiceId',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"><option value="">قبض على حساب العميل دون ربط فاتورة</option>{invoices.filter(i=>i.customer_id===form.customerId&&!['draft','cancelled'].includes(i.status)&&Number(i.total)>Number(i.amount_paid)).map(i=><option key={i.id} value={i.id}>{i.invoice_number} · متبقٍ {money(Number(i.total)-Number(i.amount_paid))}</option>)}</select></label>}
 <label className="block">البيان / الشرح *<textarea aria-label="بيان سند القبض" maxLength={1000} rows={3} value={form.description} onChange={e=>change('description',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label><label className="block">رقم مرجع (اختياري)<input aria-label="مرجع سند القبض" maxLength={200} value={form.reference} onChange={e=>change('reference',e.target.value)} className="block w-full bg-slate-800 rounded-xl p-3 mt-2"/></label>{message&&<p role="alert" className={s.error}>{message}</p>}<div className={s.buttons}><button className={s.primary} type="submit">مراجعة سند القبض</button><button type="button" onClick={()=>setOpen(false)}>إلغاء</button></div></fieldset></form>
 <aside className="min-w-0 border border-slate-700 rounded-xl p-5 bg-slate-900 self-start space-y-4"><h3 className="text-lg font-bold">ملخص سند القبض</h3><strong className="block text-3xl text-sky-300 break-words">{money(Number.isFinite(Number(form.amount))?Number(form.amount):0)}</strong><p>المستلم منه: {form.partyType==='customer'?customer?.name||'لم يُحدد':form.partyName||'لم يُحدد'}</p><p>الصندوق: {box?.name||'لم يُحدد'}</p><p>الفاتورة: {invoice?.invoice_number||(form.invoiceId?'فاتورة مرتبطة بالطلب غير متاحة في القائمة الحالية':'دون ربط')}</p>{form.partyType==='other'&&<p>الحساب المقابل: {account?.name||'لم يُحدد'}</p>}{customer&&<p className={s.hint}>رصيد العميل المسجل: {money(Number(customer.balance))}. المبلغ دون فاتورة قد ينشئ دفعة مقدمة؛ لا يصفر الرصيد تلقائياً.</p>}{review&&!uncertain&&!saving&&!saved&&<p role="status" className={s.settled}>تمت مراجعة القبض النقدي بقيمة {money(Number(form.amount))}. لم يُحفظ سند ولم تتغير أرصدة.</p>}<button type="button" disabled={preview||saving||!!saved||(!review&&!uncertain)||(!pending.current&&uncertain)} onClick={save} className="w-full rounded-xl p-3 bg-sky-500 text-slate-950 font-bold disabled:opacity-40">{saving?'جارٍ حفظ السند…':uncertain?'إعادة محاولة الطلب نفسه':preview?'معاينة فقط — لا حفظ مالي':'اعتماد سند القبض'}</button><p className={s.hint}>السند المعتمد لا يقبل التعديل أو الحذف من المسار القديم. {form.partyType==='customer'?'القبض دون فاتورة قد ينشئ رصيداً دائناً للعميل.':'يُرحّل قبض الجهة الأخرى إلى الحساب المقابل الذي اخترته.'}</p></aside></div></section>}</main>
}
