'use client'
import {useEffect,useRef,useState} from 'react'
import {listReceiptAttachments,uploadReceiptAttachment} from '@/app/dashboard/accounting/receipts/attachment-actions'
import {validateReceiptFiles} from '@/lib/receipts/bank-review'
export default function ReceiptAttachments({storeId,voucherId,initialFiles=[],preview=false,onBusyChange}:{storeId:string;voucherId:string;initialFiles?:File[];preview?:boolean;onBusyChange?:(busy:boolean)=>void}){
 const [files,setFiles]=useState<File[]>(initialFiles),[rows,setRows]=useState<{id:string;filename:string;bytes:number;status:string}[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[loaded,setLoaded]=useState(preview);const flight=useRef(false)
 async function refresh(){if(preview)return;const result=await listReceiptAttachments(storeId,voucherId);setRows(result.rows);setError(result.error||'');setLoaded(!result.error)}
 useEffect(()=>{void refresh().catch(()=>{setError('تعذر تحميل المرفقات؛ أعد المحاولة');setLoaded(false)})},[storeId,voucherId,preview])
 useEffect(()=>{onBusyChange?.(busy)},[busy,onBusyChange])
 async function upload(){if(flight.current||preview)return;const message=validateReceiptFiles(files);if(message||!files.length){setError(message||'اختر ملفات للرفع');return}flight.current=true;setBusy(true);setDone(false);setError('');let failure='';
 try{for(const file of files){const form=new FormData();form.set('file',file);const result=await uploadReceiptAttachment(storeId,voucherId,form);if(!result.ok){failure=result.error||'تعذر تأكيد الرفع';break}}
 await refresh();if(failure)setError(failure);else{setFiles([]);setDone(true)}}catch{setError('تعذر تأكيد رفع المرفقات؛ أعد رفع الملفات نفسها. السند محفوظ')}finally{flight.current=false;setBusy(false)}}
 return <section className="rounded-xl border border-slate-700 bg-slate-900 p-5 space-y-4 text-slate-100 print:hidden" dir="rtl"><h3 className="text-xl font-bold">مرفقات التحويل الخاصة</h3><p className="text-sm text-slate-300">السند محفوظ. رفع المرفقات خطوة مستقلة ولا يكرر القبض. تظهر الملفات المكتملة للمالك والمدير النشط فقط، ولا تدخل في طباعة السند.</p><p className="text-sm text-slate-300">PDF، JPG، PNG، WebP · حتى خمسة ملفات · 5 ميغابايت للملف و15 ميغابايت إجمالاً، بما فيها الرفع غير المكتمل.</p>
 {error&&<p role="alert" className="text-amber-300">{error}</p>}{done&&<p role="status" className="text-emerald-300">اكتمل رفع الملفات المختارة وربطها بالسند.</p>}
 <ul className="space-y-2">{rows.map(r=><li key={r.id} className="flex flex-wrap justify-between gap-3"><span className="break-all">{r.filename} · {(r.bytes/1024).toFixed(1)} KB</span>{r.status==='ready'?<a className="text-sky-300 underline" href={`/dashboard/accounting/receipts/attachments/${r.id}`}>تنزيل المرفق</a>:<span className="text-amber-300">رفع غير مكتمل — اختر الملف نفسه وأعد الرفع</span>}</li>)}</ul>
 <fieldset disabled={busy} className="space-y-3"><input aria-label="مرفقات السند المحفوظ" type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" className="max-w-full" onChange={e=>{const next=Array.from(e.target.files||[]);setError(validateReceiptFiles(next)||'');setFiles(next);setDone(false)}}/>{files.map((f,i)=><p className="break-all" key={i}>{f.name}</p>)}<div className="flex gap-3 flex-wrap"><button type="button" disabled={preview||!loaded||!files.length||!!validateReceiptFiles(files)} onClick={upload} className="rounded-xl bg-sky-500 px-4 py-3 font-bold disabled:opacity-40">{preview?'معاينة فقط — لا رفع':busy?'جارٍ رفع المرفقات…':'رفع المرفقات الخاصة'}</button><button type="button" onClick={()=>void refresh().catch(()=>setError('تعذر تحميل المرفقات'))}>تحديث حالة المرفقات</button></div></fieldset></section>
}
