'use client'
import {useState,useEffect,useRef} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createChequePayment} from '@/app/dashboard/accounting/payments/payment-action'
import {businessDay} from '@/lib/dashboard/simple-metrics'
import {type PaymentSupplier,type PaymentPurchase,type PaymentBox} from '@/lib/payments/presentation'
import {emptyPaymentCheque,chequePaymentTotals,validateChequePayment,endorsableCheque,type ChequePaymentReview as Review,type PaymentCheque,type PaymentBank,type PaymentPortfolio,type EndorsableCheque,type IssuedIdentity} from '@/lib/payments/cheque-review'
import s from '@/components/dashboard/accounting/invoices-list.module.css'
export default function ChequePaymentReview({suppliers,purchases,boxes,debitAccounts,banks,portfolios,incoming,issued,currency,storeId,preview,onBusyChange,onClose}:{storeId:string;preview:boolean;onBusyChange:(busy:boolean)=>void;onClose?:()=>void;suppliers:PaymentSupplier[];purchases:PaymentPurchase[];boxes:PaymentBox[];debitAccounts:{id:string;name:string;code:string}[];banks:PaymentBank[];portfolios:PaymentPortfolio[];incoming:EndorsableCheque[];issued:IssuedIdentity[];currency:string}){
 const today=businessDay().date,[input,setInput]=useState<Review>({partyType:'supplier',supplierId:'',partyName:'',date:today,amount:'0',boxId:'',purchaseId:'',description:'',reference:'',debitAccountId:'',method:'cheque',issuedPortfolioId:'',cheques:[emptyPaymentCheque(today)]}),[error,setError]=useState(''),[review,setReview]=useState(false)
 const router=useRouter(),pending=useRef<{id:string;input:Review}|null>(null),flight=useRef(false),[ready,setReady]=useState(preview),[saving,setSaving]=useState(false),[uncertain,setUncertain]=useState(false),[saved,setSaved]=useState<{id:string;number:string}|null>(null);
 useEffect(()=>{if(preview)return;try{const raw=sessionStorage.getItem(`issued-cheque-payment-pending:${storeId}`);if(!raw)return;const p=JSON.parse(raw);if(!/^[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}$/i.test(p.id)||!p.input||!['partyType','supplierId','partyName','date','amount','boxId','purchaseId','description','reference','debitAccountId','method','issuedPortfolioId'].every(k=>typeof p.input[k]==='string')||!Array.isArray(p.input.cheques)||!p.input.cheques.length||p.input.cheques.length>50||!p.input.cheques.every((c:PaymentCheque)=>c&&['source','bankId','checkId','number','amount','issueDate','dueDate'].every(k=>typeof c[k as keyof PaymentCheque]==='string')))throw Error();pending.current=p;setInput(p.input);setReview(true);setUncertain(true);setError('طلب صرف شيكات سابق غير مؤكد؛ أعد محاولة الطلب نفسه قبل إدخال سند آخر')}catch{setUncertain(true);setError('تعذر قراءة طلب صرف الشيكات السابق؛ تحقق من نتيجته قبل إدخال سند آخر')}finally{setReady(true)}},[preview,storeId]);
 useEffect(()=>{onBusyChange(!ready||saving||uncertain)},[ready,saving,uncertain,onBusyChange]);
 async function save(){if(flight.current||preview||!ready||!storeId)return;if(!pending.current){const message=validateChequePayment(input,suppliers,purchases,boxes,debitAccounts,banks,portfolios,incoming,issued,currency);if(message){setError(message);setReview(false);return}pending.current={id:crypto.randomUUID(),input:structuredClone(input)}}flight.current=true;setSaving(true);setError('');try{
 try{sessionStorage.setItem(`issued-cheque-payment-pending:${storeId}`,JSON.stringify(pending.current))}catch{setError('تعذر حفظ معرف الطلب في المتصفح؛ لم يُرسل السند');return}
 const result=await createChequePayment(storeId,pending.current.id,pending.current.input);
 if(result.ok&&result.voucherId){setSaved({id:result.voucherId,number:result.voucherNumber||''});setUncertain(false);setReview(false);pending.current=null;try{sessionStorage.removeItem(`issued-cheque-payment-pending:${storeId}`)}catch{}router.refresh()}
 else{setError(result.error||'تعذر الحفظ');setUncertain(uncertain||!!result.uncertain);if(!uncertain&&!result.uncertain){pending.current=null;try{sessionStorage.removeItem(`issued-cheque-payment-pending:${storeId}`)}catch{}setReview(false);router.refresh()}}
 }catch{setUncertain(true);setError('تعذر تأكيد نتيجة صرف الشيكات؛ أعد محاولة الطلب نفسه')}finally{flight.current=false;setSaving(false)}}
 const totals=chequePaymentTotals(input,incoming),money=(v:number)=>`${Number.isFinite(v)?v.toFixed(2):'—'} ${currency}`,field='block w-full rounded-xl p-3 mt-2 bg-slate-800 border border-slate-700',eligible=incoming.filter(c=>endorsableCheque(c,portfolios,currency,input.date)),supplier=suppliers.find(x=>x.id===input.supplierId)
 function change(p:Partial<Review>){if(saving||uncertain||saved)return;pending.current=null;setInput(v=>({...v,...p}));setReview(false);setError('')}
 function cheque(i:number,p:Partial<PaymentCheque>){change({cheques:input.cheques.map((c,n)=>n===i?{...c,...p}:c)})}
 return (
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 overflow-y-auto" dir="rtl">
    <div className="relative w-full max-w-5xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl p-6 my-8 overflow-hidden max-h-[90vh] flex flex-col">
      <div className="flex justify-between items-center pb-4 border-b border-slate-800">
        <div>
          <h2 className="text-2xl font-bold text-white">إنشاء سند صرف شيكات أو مختلط</h2>
          <p className="text-sm text-slate-400 mt-1">يحفظ إصدار الشيكات والجزء النقدي والقيد وذمة المورد وتسوية الفاتورة معاً</p>
        </div>
        {onClose && (
          <button aria-label="إغلاق نموذج الشيكات" disabled={saving||uncertain} onClick={onClose} className="text-slate-400 hover:text-white text-2xl font-bold w-10 h-10 rounded-xl hover:bg-slate-800 flex items-center justify-center transition-colors">×</button>
        )}
      </div>

      <div className="overflow-y-auto flex-1 pr-1 pl-1 py-4">
        <div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)] gap-6">
          <form className="min-w-0 space-y-5" onSubmit={e=>{e.preventDefault();const message=validateChequePayment(input,suppliers,purchases,boxes,debitAccounts,banks,portfolios,incoming,issued,currency);setError(message||'');setReview(!message)}}>
            <fieldset disabled={!ready||saving||uncertain||!!saved} className="space-y-5 min-w-0">
 <div className="flex gap-3 flex-wrap">{([['cheque','شيكات'],['split','نقدي + شيكات']] as const).map(([value,label])=><button key={value} type="button" className={`${input.method===value?s.primary:''} rounded-xl border border-slate-600 px-4 py-3`} aria-pressed={input.method===value} onClick={()=>change({method:value,amount:value==='cheque'?'0':'',boxId:''})}>{label}</button>)}</div>
 <div className="grid sm:grid-cols-2 gap-4"><label>تاريخ السند<input aria-label="تاريخ صرف الشيكات" type="date" className={field} value={input.date} onChange={e=>change({date:e.target.value})} onBlur={e=>change({date:e.target.value})}/></label><label>البيان<input aria-label="بيان صرف الشيكات" className={field} maxLength={1000} value={input.description} onChange={e=>change({description:e.target.value})}/></label></div>
 <div className="flex gap-3 flex-wrap">{([['supplier','مورد مسجل'],['other','جهة أخرى']] as const).map(([value,label])=><button type="button" key={value} className={`${input.partyType===value?s.primary:''} rounded-xl border border-slate-600 px-4 py-3`} aria-pressed={input.partyType===value} onClick={()=>change({partyType:value,supplierId:'',partyName:'',purchaseId:'',debitAccountId:'',cheques:input.cheques.map(c=>c.source==='endorse'?emptyPaymentCheque(input.date):c)})}>{label}</button>)}</div>
 {input.partyType==='supplier'?<><label className="block">المورد المستفيد<select aria-label="مورد صرف الشيكات" className={field} value={input.supplierId} onChange={e=>change({supplierId:e.target.value,purchaseId:''})}><option value="">اختر المورد</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name} {x.phone}</option>)}</select></label><label className="block">ربط فاتورة شراء (اختياري)<select aria-label="فاتورة صرف الشيكات" className={field} value={input.purchaseId} onChange={e=>change({purchaseId:e.target.value})}><option value="">على حساب المورد دون فاتورة</option>{purchases.filter(x=>x.supplier_id===input.supplierId&&x.status==='completed'&&!x.hasReturns&&x.currency===currency&&x.postedJournalId&&Number(x.total_amount)>Number(x.paid_amount)).map(x=><option key={x.id} value={x.id}>{x.invoice_number} · متبقٍ {money(Number(x.total_amount)-Number(x.paid_amount))}</option>)}</select></label><p className={s.hint}>الفواتير ذات المرتجعات تحتاج تسوية مستقلة. يراجع المتبقي مقابل مجموع النقد والشيكات.</p></>:<div className="grid sm:grid-cols-2 gap-4"><label>اسم المستفيد<input aria-label="مستفيد صرف الشيكات" className={field} maxLength={200} value={input.partyName} onChange={e=>change({partyName:e.target.value})}/></label><label>حساب المصروف أو الأصل<select aria-label="حساب صرف الشيكات المقابل" className={field} value={input.debitAccountId} onChange={e=>change({debitAccountId:e.target.value})}><option value="">اختر الحساب</option>{debitAccounts.map(a=><option key={a.id} value={a.id}>{a.code} — {a.name}</option>)}</select></label></div>}
 {input.method==='split'&&<section className="grid sm:grid-cols-2 gap-4 border border-emerald-700 rounded-xl p-4"><label>صندوق الصرف النقدي<select aria-label="صندوق الصرف المختلط" className={field} value={input.boxId} onChange={e=>change({boxId:e.target.value})}><option value="">اختر الصندوق</option>{boxes.map(b=><option key={b.id} value={b.id}>{b.name} · {money(Number(b.balance))}</option>)}</select></label><label>الجزء النقدي<input aria-label="نقد الصرف المختلط" className={field} inputMode="decimal" value={input.amount} onChange={e=>change({amount:e.target.value})}/></label></section>}
 {input.cheques.some(c=>c.source==='issue')&&<label className="block">محفظة الشيكات الصادرة<select aria-label="محفظة صرف الشيكات الصادرة" className={field} value={input.issuedPortfolioId} onChange={e=>change({issuedPortfolioId:e.target.value})}><option value="">اختر محفظة صادرة مصرحاً بها</option>{portfolios.filter(p=>p.type==='checks_issued').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 <section className="space-y-4"><h3 className="font-bold text-purple-300">بيانات الشيكات · {currency}</h3>{input.cheques.map((c,i)=>{const selected=incoming.find(x=>x.id===c.checkId);return <article key={i} className="border border-purple-700 rounded-xl p-4 space-y-4"><header className="flex justify-between gap-4"><h4>الشيك {i+1}</h4><button type="button" className="rounded-lg border border-rose-700 px-3 py-2 text-rose-300" aria-label={`حذف شيك الصرف ${i+1}`} disabled={input.cheques.length===1} onClick={()=>change({cheques:input.cheques.filter((_,n)=>n!==i)})}>حذف</button></header><label className="block">مصدر الشيك<select aria-label={`مصدر شيك الصرف ${i+1}`} className={field} value={c.source} onChange={e=>cheque(i,{...emptyPaymentCheque(input.date),source:e.target.value as 'issue'|'endorse'})}><option value="issue">إصدار شيك من حساب الشركة</option>{input.partyType==='supplier'&&<option value="endorse">تظهير شيك وارد للمورد</option>}</select></label>
 {c.source==='issue'?<><label className="block">حساب الشركة البنكي<select aria-label={`حساب بنك شيك الصرف ${i+1}`} className={field} value={c.bankId} onChange={e=>cheque(i,{bankId:e.target.value})}><option value="">اختر حساب الشركة</option>{banks.map(b=><option key={b.id} value={b.id}>{b.bank_name} · {b.account_number}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-4"><label>رقم الشيك<input aria-label={`رقم شيك الصرف ${i+1}`} className={field} maxLength={100} value={c.number} onChange={e=>cheque(i,{number:e.target.value})}/></label><label>قيمة الشيك<input aria-label={`قيمة شيك الصرف ${i+1}`} className={field} inputMode="decimal" value={c.amount} onChange={e=>cheque(i,{amount:e.target.value})}/></label><label>تاريخ الإصدار<input aria-label={`إصدار شيك الصرف ${i+1}`} className={field} type="date" value={c.issueDate} onChange={e=>cheque(i,{issueDate:e.target.value})} onBlur={e=>cheque(i,{issueDate:e.target.value})}/></label><label>تاريخ الاستحقاق<input aria-label={`استحقاق شيك الصرف ${i+1}`} className={field} type="date" value={c.dueDate} onChange={e=>cheque(i,{dueDate:e.target.value})} onBlur={e=>cheque(i,{dueDate:e.target.value})}/></label></div>{!banks.length&&<p className="text-amber-300">لا يوجد حساب شركة بنكي نشط متاح لك بعملة المتجر؛ راجع إعدادات البنك والصلاحيات.</p>}</>:<><label className="block">الشيك الوارد<select aria-label={`شيك وارد للتظهير ${i+1}`} className={field} value={c.checkId} onChange={e=>cheque(i,{checkId:e.target.value})}><option value="">اختر شيكاً متاحاً</option>{eligible.filter(x=>x.id===c.checkId||!input.cheques.some(y=>y.source==='endorse'&&y.checkId===x.id)).map(x=><option key={x.id} value={x.id}>{x.check_number} · {x.bank_name} · {money(Number(x.amount))} · {x.due_date}</option>)}</select></label>{selected&&<div className="rounded-xl bg-slate-800 p-4 space-y-2"><p>القيمة الكاملة: {money(Number(selected.amount))}</p><p>الإصدار: {selected.issue_date} · الاستحقاق: {selected.due_date}</p><p>المحفظة: {portfolios.find(p=>p.id===selected.cashbox_id)?.name||'غير متاحة'}</p></div>}<p className={s.hint}>تُظهر شيكات القبض المرتبطة والمعتمدة المتاحة فقط. يستخدم التظهير كامل قيمة الشيك؛ لا يغيّر بياناته ولا يسحبه من المحفظة أثناء المراجعة.</p>{!eligible.length&&<p className="text-amber-300">لا توجد شيكات مرتبطة متاحة للتظهير في محفظة مصرح بها وبعملة المتجر.</p>}</>}
 </article>})}<button type="button" className={`${s.primary} rounded-xl px-4 py-3`} disabled={input.cheques.length>=50} onClick={()=>change({cheques:[...input.cheques,emptyPaymentCheque(input.date)]})}>＋ إضافة شيك صرف</button></section>
 <label className="block">المرجع (اختياري)<input aria-label="مرجع صرف الشيكات" maxLength={200} className={field} value={input.reference} onChange={e=>change({reference:e.target.value})}/></label>{error&&<p role="alert" className={s.error}>{error}</p>}<button type="submit" className={`${s.primary} rounded-xl px-4 py-3`}>مراجعة صرف الشيكات والمختلط</button></fieldset></form>
  <aside className="min-w-0 border border-slate-700 rounded-xl p-5 bg-slate-900 self-start lg:sticky lg:top-6 space-y-4"><h3 className="text-xl font-bold">ملخص سند الصرف</h3><p>المستفيد: {input.partyType==='supplier'?supplier?.name||'لم يُحدد':input.partyName||'لم يُحدد'}</p><p>المبلغ النقدي: <strong>{money(totals.cash)}</strong></p><p>مجموع الشيكات: <strong className="text-purple-300">{money(totals.cheques)}</strong></p><p>عدد الشيكات: {input.cheques.length} · إصدار {input.cheques.filter(c=>c.source==='issue').length} · تظهير {input.cheques.filter(c=>c.source==='endorse').length}</p><p className="border-t border-slate-700 pt-4">إجمالي السند: <strong className="block text-3xl text-sky-300">{money(totals.total)}</strong></p><p className={s.notice}>الجزء النقدي فقط يخرج من الصندوق. إصدار الشيك لا يعني خصم البنك الآن، والتظهير ينقل الشيك الوارد للمورد عند الاعتماد.</p>{review&&!saving&&!uncertain&&!saved&&<p role="status" className={s.settled}>اجتاز السند المراجعة. لم يُحفظ سند أو شيك ولم تتغير أرصدة أو حالات.</p>}{error&&(saving||uncertain||saved)&&<p role="alert" className={s.error}>{error}</p>}{saved&&<p role="status" className={s.settled}>حُفظ سند الصرف {saved.number}. <Link href={`/dashboard/accounting/payments/print/${saved.id}`}>عرض / طباعة</Link> · <Link href="/dashboard/cheques">محفظة الشيكات</Link></p>}<button type="button" onClick={save} disabled={preview||!ready||saving||!!saved||(!review&&!uncertain)||(!pending.current&&uncertain)} className="w-full rounded-xl bg-purple-600 p-3 disabled:opacity-40">{preview?'معاينة فقط — لا حفظ مالي':saving?'جارٍ حفظ صرف الشيكات…':uncertain?'إعادة محاولة الطلب نفسه':'اعتماد صرف الشيكات والمختلط'}</button>{saved&&<button type="button" className={`${s.primary} rounded-xl px-4 py-3`} onClick={()=>{setSaved(null);setReview(false);setError('');setInput(v=>({...v,amount:v.method==='split'?'':'0',purchaseId:'',description:'',reference:'',date:businessDay().date,cheques:[emptyPaymentCheque(businessDay().date)]}))}}>سند صرف شيكات جديد</button>}<p className={s.hint}>المراجعة من بيانات التحميل؛ يعاد فحص الرصيد التاريخي والصلاحيات والفاتورة داخل معاملة الحفظ. المسودة غير متاحة بعد.</p></aside></div></div></div></div>)
}
