'use client'
import {useState,useEffect,useRef} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createCashPayment} from '@/app/dashboard/accounting/payments/payment-action'
import ChequePaymentReview from './ChequePaymentReview'
import {type PaymentBank,type PaymentPortfolio,type EndorsableCheque,type IssuedIdentity} from '@/lib/payments/cheque-review'
import {businessDay} from '@/lib/dashboard/simple-metrics'
import {paymentView,paymentNeedsReview,paymentMethods,paymentMethod,validateCashPayment,type Payment,type PaymentSupplier,type PaymentPurchase,type PaymentBox,type CashPaymentReview} from '@/lib/payments/presentation'
import s from '@/components/dashboard/accounting/invoices-list.module.css'
export default function Payments({payments,suppliers,purchases,boxes,debitAccounts,currency,initialSupplier='',preview=false,storeId='',banks=[],portfolios=[],incoming=[],issued=[]}:{banks?:PaymentBank[];portfolios?:PaymentPortfolio[];incoming?:EndorsableCheque[];issued?:IssuedIdentity[];payments:Payment[];suppliers:PaymentSupplier[];purchases:PaymentPurchase[];boxes:PaymentBox[];debitAccounts:{id:string;code:string;name:string}[];currency:string;storeId?:string;initialSupplier?:string;preview?:boolean}){
 const [q,setQ]=useState(''),[method,setMethod]=useState('all'),[supplierFilter,setSupplierFilter]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(10),[open,setOpen]=useState(!!initialSupplier),[review,setReview]=useState(false),[error,setError]=useState(''),[input,setInput]=useState<CashPaymentReview>({partyType:'supplier',supplierId:initialSupplier,partyName:'',date:businessDay().date,amount:'',boxId:'',purchaseId:'',description:'',reference:'',debitAccountId:''})
 const [chequeOpen,setChequeOpen]=useState(false),[chequeBusy,setChequeBusy]=useState(false);
 const router=useRouter(),pending=useRef<{id:string;input:CashPaymentReview}|null>(null),flight=useRef(false);
 const [ready,setReady]=useState(preview),[saving,setSaving]=useState(false),[uncertain,setUncertain]=useState(false),[saved,setSaved]=useState<{id:string;number:string}|null>(null);
 useEffect(()=>{if(preview)return;try{const raw=sessionStorage.getItem(`cash-payment-pending:${storeId}`);if(!raw){if(sessionStorage.getItem(`issued-cheque-payment-pending:${storeId}`)){setChequeOpen(true);setChequeBusy(true);setOpen(false)}return}if(sessionStorage.getItem(`issued-cheque-payment-pending:${storeId}`))throw Error();const p=JSON.parse(raw);if(!/^[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}$/i.test(p.id)||!p.input||!['partyType','supplierId','partyName','date','amount','boxId','purchaseId','description','reference','debitAccountId'].every(k=>typeof p.input[k]==='string'))throw Error();pending.current=p;setInput(p.input);setOpen(true);setReview(true);setUncertain(true);setError('طلب صرف سابق غير مؤكد؛ أعد محاولة الطلب نفسه قبل إدخال سند آخر')}catch{setOpen(true);setUncertain(true);setError('تعذر قراءة طلب الصرف السابق؛ تحقق من نتيجته قبل إدخال سند آخر')}finally{setReady(true)}},[storeId,preview]);
 async function save(){if(flight.current||preview||!storeId)return;if(!pending.current){const message=validateCashPayment(input,suppliers,purchases,boxes,debitAccounts,currency);if(message){setError(message);setReview(false);return}pending.current={id:crypto.randomUUID(),input:{...input}}}flight.current=true;setSaving(true);setError('');try{
 try{sessionStorage.setItem(`cash-payment-pending:${storeId}`,JSON.stringify(pending.current))}catch{setError('تعذر حفظ معرف الطلب في المتصفح؛ لم يُرسل السند');return}
 const result=await createCashPayment(storeId,pending.current.id,pending.current.input);
 if(result.ok&&result.voucherId){setSaved({id:result.voucherId,number:result.voucherNumber||''});setUncertain(false);setReview(false);pending.current=null;try{sessionStorage.removeItem(`cash-payment-pending:${storeId}`)}catch{}router.refresh()}
 else{setError(result.error||'تعذر الحفظ');setUncertain(uncertain||!!result.uncertain);if(!uncertain&&!result.uncertain){pending.current=null;try{sessionStorage.removeItem(`cash-payment-pending:${storeId}`)}catch{}setReview(false);router.refresh()}}
 }catch{setUncertain(true);setError('تعذر تأكيد نتيجة الصرف؛ أعد محاولة الطلب نفسه')}finally{flight.current=false;setSaving(false)}}
 const v=paymentView(payments,{q,method,supplier:supplierFilter,from,to,page,size}),money=(n:number)=>`${Number.isFinite(Number(n))?Number(n).toFixed(2):'—'} ${currency}`,supplier=suppliers.find(x=>x.id===input.supplierId),box=boxes.find(x=>x.id===input.boxId),purchase=purchases.find(x=>x.id===input.purchaseId),account=debitAccounts.find(x=>x.id===input.debitAccountId),field='block w-full rounded-xl p-3 mt-2 bg-slate-800 border border-slate-700'
 function change(p:Partial<CashPaymentReview>){if(saving||uncertain||saved)return;pending.current=null;setInput(v=>({...v,...p}));setReview(false);setError('')}
 return <main className={s.page} dir="rtl"><Link className={s.back} href="/dashboard/accounting-hub">← الإدارة المالية والمحاسبية</Link><header className={s.header}><div><h1>سندات الصرف</h1><p>مدفوعات الموردين والجهات الأخرى، والصرف النقدي الفعلي</p></div><div className={s.buttons}><button className="rounded-xl bg-rose-500 px-5 py-3 font-bold text-white" disabled={!ready||saving||uncertain||chequeBusy} onClick={()=>{setChequeOpen(false);if(saved){setSaved(null);setInput(v=>({...v,amount:'',purchaseId:'',description:'',reference:'',date:businessDay().date}));setOpen(true)}else setOpen(!open);setReview(false);setError('')}}>{saved?'＋ سند صرف نقدي جديد':open?'إغلاق نموذج الصرف':'＋ سند صرف نقدي جديد'}</button><button className={s.primary} disabled={!ready||saving||uncertain||chequeBusy} onClick={()=>{setChequeOpen(!chequeOpen);setOpen(false)}}>{chequeOpen?'إغلاق نموذج الشيكات':'＋ صرف شيكات أو مختلط'}</button></div></header>
 <div className={s.stats}>{[['إجمالي السندات',money(v.total),'◈'],['الصرف النقدي الفعلي',money(v.cash),'↗'],['شيكات اسمية',money(v.cheques),'▤'],['عدد السندات',v.filtered.length,'▦']].map(([title,value,icon])=><section key={title} className={s.stat}><span className={s.icon}>{icon}</span><div><span>{title}</span><strong>{value}</strong><small>حسب الفلاتر · قيمة الشيك لا تعني صرفاً نقدياً</small></div></section>)}</div>
 <section className={s.panel}><div className={s.filters}><input aria-label="بحث سندات الصرف" placeholder="رقم السند، المستفيد، البيان أو المرجع…" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/><label>المورد<select aria-label="تصفية مورد الصرف" value={supplierFilter} onChange={e=>{setSupplierFilter(e.target.value);setPage(1)}}><option value="">جميع الموردين والجهات</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>من تاريخ<input aria-label="بداية فترة الصرف" type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label>إلى تاريخ<input aria-label="نهاية فترة الصرف" type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label><button onClick={()=>{setQ('');setMethod('all');setSupplierFilter('');setFrom('');setTo('');setPage(1)}}>مسح الفلاتر</button></div><div className={s.tabs}>{Object.entries({all:'الكل',...paymentMethods}).map(([key,label])=><button key={key} aria-pressed={method===key} onClick={()=>{setMethod(key);setPage(1)}}>{label}</button>)}</div></section>
 {v.error&&<p role="alert" className={s.error}>{v.error}</p>}{v.review>0&&<p className={s.notice}>{v.review} سند يحتاج مراجعة ربط القيد أو مطابقة النقد والشيكات؛ لا تُغيّر الأرصدة تلقائياً.</p>}
 <div className={s.tableWrap}><table><thead><tr>{['رقم السند','التاريخ','المستفيد','طريقة الصرف','الصندوق / البيان','فاتورة الشراء','المبلغ','القيد والمطابقة','المستندات'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{v.rows.map(p=><tr key={p.id}><td className={s.number}>{p.voucher_number}</td><td>{p.date}</td><td>{p.party_name||'غير محدد'}</td><td><span className={s.badge}>{paymentMethods[paymentMethod(p.payment_method)]}</span></td><td>{p.boxName||'دون صندوق نقدي'}<small>{p.description||'—'}</small><small>{p.reference}</small></td><td>{p.purchase_invoice_id?<Link href={`/dashboard/purchases/${p.purchase_invoice_id}`}>{p.purchaseNumber||'فاتورة مرتبطة'}</Link>:'غير مرتبط'}</td><td>{money(Number(p.amount))}</td><td><span className={`${s.badge} ${paymentNeedsReview(p)?s.unpaid:s.paid}`}>{paymentNeedsReview(p)?'يحتاج مراجعة':p.actualCash>0?'قيد مرحّل · النقد مطابق':'قيد مرحّل · سند غير نقدي'}</span></td><td><div className={s.rowActions}><Link href={`/dashboard/accounting/payments/print/${p.id}`}>عرض / طباعة</Link>{p.postedJournalId&&<Link href={`/dashboard/accounting/journal/print/${p.postedJournalId}`}>القيد</Link>}</div></td></tr>)}{!v.rows.length&&<tr><td colSpan={9} className={s.empty}>لا توجد سندات ضمن الفلاتر الحالية.</td></tr>}</tbody></table></div>
 <footer className={s.pagination}><div>لكل صفحة<select aria-label="عدد سندات الصرف في الصفحة" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select><span>الصفحة {v.page} من {v.pages} · {v.filtered.length} سند</span></div><div><button disabled={v.page===1} onClick={()=>setPage(v.page-1)}>السابق</button><button disabled={v.page===v.pages} onClick={()=>setPage(v.page+1)}>التالي</button></div></footer>
 {chequeOpen&&<ChequePaymentReview storeId={storeId} preview={preview} onBusyChange={setChequeBusy} onClose={()=>setChequeOpen(false)} suppliers={suppliers} purchases={purchases} boxes={boxes} debitAccounts={debitAccounts} banks={banks} portfolios={portfolios} incoming={incoming} issued={issued} currency={currency}/>}
 {open&&(
  <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 overflow-y-auto" dir="rtl">
    <div className="relative w-full max-w-4xl bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl p-6 my-8 overflow-hidden max-h-[90vh] flex flex-col">
      <div className="flex justify-between items-center pb-4 border-b border-slate-800">
        <div>
          <h2 className="text-2xl font-bold text-white">إنشاء سند صرف نقدي</h2>
          <p className="text-sm text-slate-400 mt-1">يحفظ سند الصرف وحركة الصندوق والقيد وذمة المورد وتسوية فاتورة الشراء معاً</p>
        </div>
        <button aria-label="إغلاق نموذج الصرف" disabled={saving||uncertain} onClick={()=>setOpen(false)} className="text-slate-400 hover:text-white text-2xl font-bold w-10 h-10 rounded-xl hover:bg-slate-800 flex items-center justify-center transition-colors">×</button>
      </div>
      <div className="overflow-y-auto flex-1 pr-1 pl-1 py-4">
        <div className="grid lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)] gap-6">
          <form className="space-y-5 min-w-0" onSubmit={e=>{e.preventDefault();const message=validateCashPayment(input,suppliers,purchases,boxes,debitAccounts,currency);setError(message||'');setReview(!message)}}>
            <fieldset disabled={saving||uncertain||!!saved} className="space-y-5 min-w-0">
              <div className="flex gap-3 flex-wrap">
                <button type="button" className={input.partyType==='supplier'?s.primary:''} aria-pressed={input.partyType==='supplier'} onClick={()=>change({partyType:'supplier',supplierId:'',partyName:'',purchaseId:'',debitAccountId:''})}>مورد مسجل</button>
                <button type="button" className={input.partyType==='other'?s.primary:''} aria-pressed={input.partyType==='other'} onClick={()=>change({partyType:'other',supplierId:'',partyName:'',purchaseId:'',debitAccountId:''})}>جهة أخرى</button>
                <span className="text-rose-300">طريقة الصرف: نقدي</span>
              </div>
              <label className="block">تاريخ السند<input aria-label="تاريخ سند الصرف" type="date" className={field} value={input.date} onChange={e=>change({date:e.target.value})}/></label>
              {input.partyType==='supplier'?<label className="block">المورد المستفيد<select aria-label="مورد الصرف النقدي" className={field} value={input.supplierId} onChange={e=>change({supplierId:e.target.value,purchaseId:''})}><option value="">اختر المورد</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.name} {x.phone}</option>)}</select></label>:<><label className="block">اسم المستفيد<input aria-label="اسم مستفيد الصرف" className={field} maxLength={200} value={input.partyName} onChange={e=>change({partyName:e.target.value})}/></label><label className="block">حساب المصروف أو الأصل<select aria-label="حساب الصرف المقابل" className={field} value={input.debitAccountId} onChange={e=>change({debitAccountId:e.target.value})}><option value="">اختر الحساب المقابل</option>{debitAccounts.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</select></label></>}
              <label className="block">صندوق الصرف<select aria-label="صندوق الصرف النقدي" className={field} value={input.boxId} onChange={e=>change({boxId:e.target.value})}><option value="">اختر صندوقاً مصرحاً به</option>{boxes.map(x=><option key={x.id} value={x.id}>{x.name} · الرصيد {money(x.balance)}</option>)}</select></label>{!boxes.length&&<p className="text-amber-300">لا يوجد صندوق نقدي نشط بحساب مطابق وصلاحية صرف؛ راجع إعدادات الخزينة.</p>}
              <label className="block">المبلغ النقدي<input aria-label="مبلغ الصرف النقدي" inputMode="decimal" className={field} value={input.amount} onChange={e=>change({amount:e.target.value})}/></label>
              <label className="block">البيان<textarea aria-label="بيان سند الصرف" className={field} rows={3} maxLength={1000} value={input.description} onChange={e=>change({description:e.target.value})}/></label>
              {input.partyType==='supplier'&&<label className="block">ربط فاتورة شراء (اختياري) · الفواتير ذات المرتجعات تحتاج تسوية مستقلة<select aria-label="فاتورة الصرف النقدي" className={field} value={input.purchaseId} onChange={e=>change({purchaseId:e.target.value})}><option value="">على حساب المورد دون فاتورة</option>{purchases.filter(x=>x.supplier_id===input.supplierId&&x.status==='completed'&&!x.hasReturns&&x.currency===currency&&x.postedJournalId&&Number(x.total_amount)>Number(x.paid_amount)).map(x=><option key={x.id} value={x.id}>{x.invoice_number} · متبقٍ {money(Number(x.total_amount)-Number(x.paid_amount))}</option>)}</select></label>}
              <label className="block">المرجع (اختياري)<input aria-label="مرجع سند الصرف" className={field} maxLength={200} value={input.reference} onChange={e=>change({reference:e.target.value})}/></label>
              {error&&<p role="alert" className={s.error}>{error}</p>}
              <button type="submit" className="rounded-xl bg-rose-500 px-5 py-3 font-bold">مراجعة سند الصرف</button>
            </fieldset>
          </form>
          <aside className="self-start rounded-xl border border-slate-700 bg-slate-900 p-5 space-y-4 min-w-0">
            <h3 className="text-xl font-bold">ملخص سند الصرف</h3>
            <strong className="block text-3xl text-rose-300">{money(Number(input.amount||0))}</strong>
            <p>المستفيد: {input.partyType==='supplier'?supplier?.name||'لم يُحدد':input.partyName||'لم يُحدد'}</p>
            <p>الصندوق: {box?.name||'لم يُحدد'}</p>
            {box&&<p>الرصيد النقدي الحالي: {money(box.balance)}</p>}
            <p>الفاتورة: {purchase?.invoice_number||'دون ربط'}</p>
            {supplier&&<p className={s.hint}>رصيد المورد المسجل: {money(Number(supplier.balance))}. الدفع دون فاتورة قد ينشئ دفعة مقدمة؛ لا يصفّر الرصيد تلقائياً.</p>}
            {account&&input.partyType==='other'&&<p>الحساب المقابل: {account.name}</p>}
            <p className={s.hint}>الرصيد المعروض لحظة تحميل الصفحة. يعاد فحص الصندوق والفاتورة والصلاحيات داخل معاملة الحفظ، بما فيها الرصيد في تاريخ الصرف والحركات اللاحقة.</p>
            {review&&!saving&&!uncertain&&!saved&&<p role="status" className={s.settled}>اجتاز الصرف المراجعة. لم يُحفظ سند ولم تتغير أرصدة.</p>}
            {error&&(saving||uncertain||saved)&&<p role="alert" className={s.error}>{error}</p>}
            {saved&&<p role="status" className={s.settled}>حُفظ سند الصرف {saved.number}. <Link href={`/dashboard/accounting/payments/print/${saved.id}`}>عرض / طباعة</Link></p>}
            <button type="button" onClick={save} disabled={preview||!ready||saving||!!saved||(!review&&!uncertain)||(!pending.current&&uncertain)} className="w-full rounded-xl bg-rose-500 p-3 font-bold disabled:opacity-40">{preview?'معاينة فقط — لا حفظ مالي':saving?'جارٍ حفظ الصرف…':uncertain?'إعادة محاولة الطلب نفسه':'اعتماد سند الصرف النقدي'}</button>
          </aside>
        </div>
      </div>
    </div>
  </div>
)}</main>
}
