'use client'
import {useRef,useState} from 'react'
import Link from 'next/link'
import {useRouter} from 'next/navigation'
import {createPurchase,type PurchaseInput} from './create-purchase-action'
import {purchaseSummary,validatePurchase,type PurchaseRow} from '@/lib/purchases/form'
import styles from '@/components/dashboard/accounting/new-invoice.module.css'
interface Supplier{id:string;name:string;phone:string|null;balance:number}
interface Product{id:string;name:string;sku?:string|null;barcode?:string|null;cost_price:number|null;stock_quantity:number;price:number}
export default function CreatePurchaseClient({store,suppliers,products,cashBoxes=[],preview=false}:{store:{id:string;name:string;currency_code:string};suppliers:Supplier[];products:Product[];cashBoxes?:{id:string;name:string}[];preview?:boolean}){
 const router=useRouter(),request=useRef<{id:string;payload:PurchaseInput}|null>(null),lock=useRef(false);const [saving,setSaving]=useState(false),[uncertain,setUncertain]=useState(false),[box,setBox]=useState('');
 const [number,setNumber]=useState(''),[supplierNumber,setSupplierNumber]=useState(''),[date,setDate]=useState(()=>new Date().toLocaleDateString('en-CA')),[supplier,setSupplier]=useState(''),[method,setMethod]=useState('credit'),[items,setItems]=useState<PurchaseRow[]>([]),[search,setSearch]=useState(''),[discount,setDiscount]=useState('0'),[tax,setTax]=useState('0'),[paid,setPaid]=useState('0'),[notes,setNotes]=useState(''),[review,setReview]=useState(false),[error,setError]=useState('')
 const raw=purchaseSummary(items,discount,tax,paid),summary=purchaseSummary(items,discount,tax,method==='cash'?String(raw.total):method==='credit'?'0':paid),currency=store.currency_code||'ILS',money=(n:number)=>Number.isFinite(n)?`${n.toLocaleString('en-GB',{minimumFractionDigits:2,maximumFractionDigits:2})} ${currency}`:'—';const results=search.trim()?products.filter(p=>`${p.name} ${p.sku||''} ${p.barcode||''}`.toLowerCase().includes(search.trim().toLowerCase())).slice(0,10):[]
 function changed(){setReview(false);setError('')}
 function add(p:Product){changed();setItems(rs=>{const found=rs.find(r=>r.product_id===p.id);return found?rs.map(r=>r.product_id===p.id?{...r,quantity:String(Number(r.quantity)+1)}:r):[...rs,{product_id:p.id,product_name:p.name,quantity:'1',unit_price:String(p.cost_price??0)}]});setSearch('')}
 function update(id:string,field:'quantity'|'unit_price',value:string){changed();setItems(rs=>rs.map(r=>r.product_id===id?{...r,[field]:value}:r))}
 function check(e:React.FormEvent){e.preventDefault();const invalid=validatePurchase({invoice_number:number,invoice_date:date,supplier_id:supplier,items,discount,tax,paid:method==='cash'?String(summary.total):method==='credit'?'0':paid,method},products.map(p=>p.id),suppliers.map(s=>s.id));setError(invalid||'');setReview(!invalid)}
 async function save(mode:'draft'|'post') {if(lock.current||preview)return;if(!uncertain){const payload:PurchaseInput={invoice_number:number,invoice_date:date,supplier_id:supplier,supplier_number:supplierNumber,cash_box_id:box,mode,method,paid:mode==='draft'?'0':String(summary.paid),discount,tax,notes,items};const invalid=validatePurchase({...payload,method:mode==='draft'?'credit':method},products.map(p=>p.id),suppliers.map(s=>s.id));if(invalid){setError(invalid);return}if(Number(tax)!==0){setError('يلزم إعداد حساب ضريبة المشتريات قبل حفظ فاتورة بضريبة.');return}if(mode==='post'&&summary.paid>0&&!box){setError('اختر صندوق الصرف.');return}request.current={id:crypto.randomUUID(),payload}}if(!request.current)return;lock.current=true;setSaving(true);try{const r=await createPurchase(store.id,request.current.id,request.current.payload);if(r.ok){router.push('/dashboard/purchases');router.refresh()}else{setError(r.error||'تعذر الحفظ');setUncertain(!!r.uncertain);if(!r.uncertain)request.current=null}}catch{setUncertain(true);setError('تعذر تأكيد الحفظ؛ أعد الطلب نفسه.')}finally{lock.current=false;setSaving(false)}}
 const input='w-full min-w-0 bg-slate-800 border border-slate-600 rounded-xl p-3 mt-2 text-sm',supplierInfo=suppliers.find(s=>s.id===supplier)
 return <main dir="rtl" className="text-slate-100 space-y-6"><Link href="/dashboard/purchases-hub" className="text-slate-400 text-sm">← العودة إلى إدارة المشتريات</Link><header><p className="text-sm text-slate-400">المشتريات / فاتورة جديدة</p><h1 className="text-2xl font-bold mt-3">تسجيل فاتورة مشتريات جديدة</h1><p className="text-slate-400 mt-2 text-sm">أدخل الأصناف وتكاليفها، ثم راجع الإجمالي والدفعة.</p></header><p className="text-sm text-slate-400">الحفظ المعتمد يحدّث المخزون وحساب المورد ويسجل الدفعة والقيد معاً. المسودة بلا أثر مالي. {preview?'الحفظ معطل في المعاينة.':''}</p>
 <form onSubmit={check} className={styles.form} onChange={()=>setReview(false)}><fieldset disabled={saving||uncertain} className={styles.main}><section className={styles.panel}><h2 className="font-bold mb-5">معلومات الفاتورة والمورد</h2><div className="grid sm:grid-cols-2 gap-4"><label>رقم الفاتورة بالنظام *<input className={input} maxLength={100} value={number} onChange={e=>setNumber(e.target.value)} placeholder="PUR-..."/></label><label>رقم فاتورة المورد<input className={input} maxLength={100} value={supplierNumber} onChange={e=>setSupplierNumber(e.target.value)} placeholder="INV-9942"/></label><label>تاريخ الفاتورة *<input type="date" className={input} value={date} onChange={e=>setDate(e.target.value)}/></label><label>المورد *<select className={input} value={supplier} onChange={e=>setSupplier(e.target.value)}><option value="">اختر المورد</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}{s.phone?` (${s.phone})`:''}</option>)}</select></label></div>{supplierInfo&&<p className="text-sm text-slate-400 mt-4">رصيد المورد المسجل: {money(Number(supplierInfo.balance))}</p>}<p className="text-xs text-slate-400 mt-4">العملة: {currency}</p></section>
 <section className={styles.panel}><h2 className="font-bold mb-4">أصناف الفاتورة</h2><label className="text-sm text-sky-300">البحث بالاسم أو الكود أو الباركود<input className={input} aria-label="البحث عن صنف" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();if(results.length===1)add(results[0])}}} placeholder="اكتب اسم الصنف أو امسح الباركود..."/></label>{search.trim()&&<div className="max-h-52 overflow-auto border border-slate-700 rounded-xl mt-2">{results.map(p=><button key={p.id} type="button" onClick={()=>add(p)} className="w-full flex flex-wrap justify-between gap-2 text-right p-3 hover:bg-sky-950"><span>{p.name} <small className="text-slate-400">{p.sku||p.barcode}</small></span><span className="text-sky-300 text-xs">تكلفة {money(p.cost_price??0)} · إضافة ＋</span></button>)}{!results.length&&<p className="p-4 text-sm text-slate-400">لا توجد أصناف مطابقة.</p>}</div>}
 {!items.length?<div className="text-center p-12 text-slate-400"><svg className="mx-auto text-sky-300 mb-5" width="72" height="72" viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10"/></svg><h3 className="font-bold text-white">ابدأ بإضافة أصناف إلى الفاتورة</h3><p className="text-sm mt-3">ابحث بالاسم أو الكود أو امسح الباركود لإضافته</p></div>:<div className="overflow-x-auto mt-5"><table className="w-full text-sm"><thead className="text-slate-400"><tr><th className="p-3 text-right">الصنف</th><th>الكمية</th><th>تكلفة الوحدة</th><th>الإجمالي</th><th>إجراءات</th></tr></thead><tbody>{items.map(r=><tr key={r.product_id} className="border-t border-slate-700"><td className="p-3">{r.product_name}</td><td className="p-2"><input aria-label={`كمية ${r.product_name}`} type="number" min="0.01" step="0.01" value={r.quantity} onChange={e=>update(r.product_id,'quantity',e.target.value)} className="w-20 bg-slate-800 rounded-lg p-2"/></td><td className="p-2"><input aria-label={`تكلفة ${r.product_name}`} type="number" min="0" step="0.01" value={r.unit_price} onChange={e=>update(r.product_id,'unit_price',e.target.value)} className="w-24 bg-slate-800 rounded-lg p-2"/></td><td className="p-2 whitespace-nowrap">{money(Number(r.quantity)*Number(r.unit_price))}</td><td><button type="button" aria-label={`حذف ${r.product_name}`} className="text-rose-400 p-3" onClick={()=>{changed();setItems(rs=>rs.filter(x=>x.product_id!==r.product_id))}}>×</button></td></tr>)}</tbody></table></div>}</section>
 {review&&<section className={styles.review} role="status"><h2 className="font-bold">مراجعة الفاتورة</h2><p>{number} · {date} · {supplierInfo?.name} · {items.length} صنف</p><p>الإجمالي: {money(summary.total)} · الدفعة المقترحة: {money(summary.paid)} · المتبقي: {money(summary.remaining)}</p><p className="text-sm text-amber-200">لم تُحفظ فاتورة أو دفعة، ولم يتغير المخزون أو حساب المورد.</p></section>}</fieldset>
 <aside className={styles.side}><fieldset disabled={saving||uncertain} className="space-y-4"><section className={styles.panel}><h2 className="font-bold">ملخص الفاتورة</h2><div className={styles.summary}><span>عدد الأصناف</span><span>{items.length}</span></div><div className={styles.summary}><span>المجموع الفرعي</span><span>{money(summary.subtotal)}</span></div><label className="block mt-4">الخصم ({currency})<input aria-label="الخصم" type="number" min="0" step="0.01" className={input} value={discount} onChange={e=>setDiscount(e.target.value)}/></label><label className="block mt-4">ضريبة بعد الخصم (%)<input disabled aria-label="نسبة الضريبة" type="number" min="0" max="100" step="0.01" className={input} value={tax} onChange={e=>setTax(e.target.value)}/></label><p className="text-xs text-amber-200 mt-2">الضريبة متوقفة حتى إعداد حساب ضريبة المشتريات.</p><div className={styles.summary}><span>قيمة الضريبة</span><span>{money(summary.tax)}</span></div><div className={styles.summary}><span>الإجمالي الكلي</span><strong>{money(summary.total)}</strong></div></section>
 <section className={styles.panel}><h2 className="font-bold">الدفع المقترح</h2><div className={styles.tabs}>{[['credit','آجل'],['cash','نقدي كامل'],['partial','جزئي']].map(([v,l])=><button key={v} type="button" aria-pressed={method===v} onClick={()=>{changed();setMethod(v)}}>{l}</button>)}</div>{method==='partial'&&<label>الدفعة المقترحة<input type="number" min="0.01" step="0.01" aria-label="الدفعة المقترحة" className={input} value={paid} onChange={e=>setPaid(e.target.value)}/></label>}<label className="block mt-3">صندوق الصرف<select disabled={saving||uncertain||method==='credit'} className={input} value={box} onChange={e=>setBox(e.target.value)}><option value="">اختر الصندوق</option>{cashBoxes.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p className="text-sm mt-3">المتبقي على حساب المورد: {money(summary.remaining)}</p><p className={styles.notice}>سيسجل سند صرف نقدي واحد بقيمة الدفعة ويرتبط بالفاتورة.</p></section>
 <section className={styles.panel}><label>ملاحظات الفاتورة<textarea maxLength={2000} className={input} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="أضف ملاحظات على الفاتورة..."/></label></section>
 </fieldset><div className={styles.actions}>{error&&<p role="alert" className="text-rose-400">{error}</p>}<button disabled={saving||uncertain} type="submit">مراجعة فاتورة المشتريات</button><button type="button" disabled={saving||preview||(!uncertain&&!review)} onClick={()=>save('post')} className="disabled:opacity-40">{saving?'جارٍ الحفظ...':uncertain?'إعادة محاولة الطلب نفسه':'حفظ واعتماد الفاتورة'}</button><button type="button" disabled={saving||preview||uncertain} onClick={()=>save('draft')} className="disabled:opacity-40">حفظ كمسودة</button>{uncertain&&<p className="text-amber-200 text-sm">نتيجة الحفظ غير مؤكدة. ثُبتت بيانات الطلب؛ أعد المحاولة دون تغييرها أو إنشاء فاتورة أخرى.</p>}<Link href="/dashboard/purchases" className="text-center text-slate-400 p-3">إلغاء</Link></div></aside></form></main>
}
