import {redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import {getStoreForUser} from '@/lib/supabase/getStore'
import {allRows} from '@/lib/dashboard/load-simple-dashboard'
import {type Receipt,type ReceiptCustomer,type ReceiptInvoice} from '@/lib/receipts/presentation'
import Receipts from '@/components/dashboard/receipts/Receipts'
export const metadata={title:'سندات القبض — Bazarko'}
export default async function Page({searchParams}:{searchParams?:{customer_id?:string}}){const c=createClient(),{data:{user}}=await c.auth.getUser();if(!user)redirect('/login');const id=await getStoreForUser(c,user.id);if(!id)redirect('/onboarding');const {data:store,error}=await c.from('stores').select('id,name,currency_code,owner_id').eq('id',id).single();if(error||!store)throw Error('تعذر تحميل المتجر');const currency=store.currency_code||'ILS';const [receipts,customers,invoices,boxes,accounts,journals,movements,checks,members,permissions]=await Promise.all([
allRows<Receipt>((a,b)=>c.from('vouchers').select('id,voucher_number,date,created_at,amount,cash_amount,checks_amount,payment_method,party_name,customer_id,supplier_id,invoice_id,purchase_return_id,description,reference,cash_box_id,journal_entry_id').eq('store_id',id).eq('type','receipt').order('id').range(a,b)),
allRows<ReceiptCustomer>((a,b)=>c.from('customers').select('id,name,phone,balance').eq('store_id',id).eq('is_active',true).order('id').range(a,b)),
allRows<ReceiptInvoice>((a,b)=>c.from('invoices').select('id,customer_id,invoice_number,issue_date,total,amount_paid,status').eq('store_id',id).not('status','in','(draft,cancelled)').order('id').range(a,b)),
allRows<{id:string;name:string;account_id:string;type:string}>((a,b)=>c.from('cash_boxes').select('id,name,account_id,type').eq('store_id',id).eq('is_active',true).in('type',['cash','checks_received']).order('id').range(a,b)),
allRows<{id:string;name:string;code:string;type:string;currency:string;account_tag:string|null;normal_balance:string}>((a,b)=>c.from('accounts').select('id,name,code,type,currency,account_tag,normal_balance').eq('store_id',id).eq('is_active',true).eq('is_group',false).eq('currency',currency).order('id').range(a,b)),
allRows<{id:string;ref_id:string|null}>((a,b)=>c.from('journal_entries').select('id,ref_id').eq('store_id',id).eq('status','posted').order('id').range(a,b)),
allRows<{ref_id:string|null;amount:number}>((a,b)=>c.from('cash_movements').select('id,ref_id,amount').eq('store_id',id).eq('direction','in').order('id').range(a,b)),
allRows<{voucher_id:string|null}>((a,b)=>c.from('checks').select('id,voucher_id').eq('store_id',id).order('id').range(a,b)),
allRows<{role:string}>((a,b)=>c.from('store_members').select('id,role').eq('store_id',id).eq('profile_id',user.id).eq('is_active',true).order('id').range(a,b)),
allRows<{cash_box_id:string;can_receipt:boolean}>((a,b)=>c.from('user_cash_box_permissions').select('id,cash_box_id,can_receipt').eq('store_id',id).eq('user_id',user.id).order('id').range(a,b))]);
const privileged=store.owner_id===user.id||members.some(m=>['owner','admin'].includes(m.role));const allowedBoxes=boxes.filter(b=>b.type==='cash'&&accounts.some(a=>a.id===b.account_id&&['CASH','PETTY_CASH'].includes(a.account_tag||'')&&a.normal_balance==='debit')&&(privileged||permissions.some(p=>p.cash_box_id===b.id&&p.can_receipt)));for(const r of receipts){const cash=movements.filter(m=>m.ref_id===r.id);r.actualCash=cash.reduce((n,m)=>n+Number(m.amount),0);r.movementCount=cash.length;r.chequeCount=checks.filter(k=>k.voucher_id===r.id).length;r.postedJournalId=journals.find(j=>j.id===r.journal_entry_id&&j.ref_id===r.id)?.id||journals.find(j=>j.ref_id===r.id)?.id||null}return <div className="p-4 sm:p-6"><Receipts receipts={receipts} storeId={id} initialCustomer={customers.some(c=>c.id===searchParams?.customer_id)?searchParams?.customer_id:undefined} customers={customers} invoices={invoices.filter(i=>Number(i.total)>Number(i.amount_paid))} cashBoxes={allowedBoxes.map(b=>({id:b.id,name:b.name}))} portfolios={boxes.filter(b=>b.type==='checks_received'&&accounts.some(a=>a.id===b.account_id&&a.account_tag==='CHECKS_PORTFOLIO'&&a.type==='asset'&&a.normal_balance==='debit')&&(privileged||permissions.some(p=>p.cash_box_id===b.id&&p.can_receipt))).map(b=>({id:b.id,name:b.name}))} creditAccounts={accounts.filter(a=>['revenue','liability','equity'].includes(a.type)&&a.normal_balance==='credit').map(a=>({id:a.id,name:a.name,code:a.code}))} currency={currency}/></div>}
