export interface Receipt {id:string;voucher_number:string;date:string;created_at:string;amount:number;cash_amount:number|null;checks_amount:number|null;payment_method:string;party_name:string|null;customer_id:string|null;supplier_id:string|null;invoice_id:string|null;purchase_return_id:string|null;description:string|null;reference:string|null;cash_box_id:string|null;journal_entry_id:string|null;postedJournalId?:string|null;actualCash:number;movementCount:number;chequeCount:number}
export interface ReceiptCustomer {id:string;name:string;phone:string|null;balance:number}
export interface ReceiptInvoice {id:string;customer_id:string|null;invoice_number:string;issue_date:string;total:number;amount_paid:number;status:string}
export interface CashReview {partyType:'customer'|'other';customerId:string;partyName:string;date:string;amount:string;boxId:string;invoiceId:string;description:string;reference:string;creditAccountId:string}
export const receiptMethods:Record<string,string>={cash:'نقدي',cheque:'شيكات',split:'نقدي + شيكات',bank:'تحويل بنكي',card:'بطاقة',unknown:'طريقة غير معروفة'}
export function receiptMethod(raw:string){return raw==='check'?'cheque':raw==='transfer'?'bank':Object.prototype.hasOwnProperty.call(receiptMethods,raw)?raw:'unknown'}
export function dateValid(s:string){return !s||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s))&&new Date(s).toISOString().slice(0,10)===s)}
export function declaredCash(v:Receipt){return Number(v.cash_amount??(receiptMethod(v.payment_method)==='cash'?v.amount:0))}
export function receiptNeedsReview(v:Receipt){const cash=declaredCash(v);return !v.postedJournalId||Math.abs(cash-Number(v.actualCash))>.005||(cash>0&&v.movementCount!==1)||(cash===0&&v.movementCount!==0)}
export function receiptView(receipts:Receipt[],q:string,method:string,from:string,to:string,page:number,size:number){if(!dateValid(from)||!dateValid(to)||(from&&to&&from>to))return {error:'راجع تواريخ الفترة؛ البداية لا تتجاوز النهاية',filtered:[],rows:[],page:1,pages:1,total:0,cash:0,cheques:0,review:0};const query=q.trim().toLowerCase();const filtered=receipts.filter(v=>`${v.voucher_number} ${v.party_name||''} ${v.description||''} ${v.reference||''}`.toLowerCase().includes(query)&&(method==='all'||receiptMethod(v.payment_method)===method)&&(!from||v.date>=from)&&(!to||v.date<=to)).sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));const count=[10,25,50].includes(size)?size:10,pages=Math.max(1,Math.ceil(filtered.length/count)),current=Math.max(1,Math.min(Number.isFinite(page)?Math.floor(page):1,pages));const totals=filtered.reduce((s,v)=>({total:s.total+Math.round(Number(v.amount)*100),cash:s.cash+Math.round(Number(v.actualCash)*100),cheques:s.cheques+Math.round(Number(v.checks_amount??(receiptMethod(v.payment_method)==='cheque'?v.amount:0))*100),review:s.review+Number(receiptNeedsReview(v))}),{total:0,cash:0,cheques:0,review:0});return {error:null,filtered,rows:filtered.slice((current-1)*count,current*count),page:current,pages,...totals,total:totals.total/100,cash:totals.cash/100,cheques:totals.cheques/100}}
export function validateCashReview(input:CashReview,customers:ReceiptCustomer[],invoices:ReceiptInvoice[],boxes:{id:string}[],accounts:{id:string}[]){if(!dateValid(input.date)||!input.date)return 'أدخل تاريخاً صحيحاً للسند';if(!/^\d+(\.\d{1,2})?$/.test(input.amount)||!Number.isFinite(Number(input.amount))||Number(input.amount)<=0||Number(input.amount)>999999999)return 'أدخل مبلغاً موجباً بمنزلتين عشريتين كحد أقصى';if(!boxes.some(b=>b.id===input.boxId))return 'اختر صندوقاً نقدياً مصرحاً به';if(!input.description.trim()||input.description.length>1000||input.reference.length>200)return 'أدخل البيان ضمن الحدود المسموحة';if(input.partyType==='customer'){if(!customers.some(c=>c.id===input.customerId))return 'اختر عميلاً من المتجر';if(input.invoiceId){const inv=invoices.find(i=>i.id===input.invoiceId&&i.customer_id===input.customerId&&!['draft','cancelled'].includes(i.status));if(!inv)return 'الفاتورة لا تخص العميل أو غير معتمدة';if(input.date<inv.issue_date)return 'تاريخ القبض لا يسبق الفاتورة';if(Math.round(Number(input.amount)*100)>Math.round((Number(inv.total)-Number(inv.amount_paid))*100))return 'المبلغ يتجاوز المتبقي على الفاتورة'}}else if(input.partyType==='other'){if(!input.partyName.trim()||input.partyName.length>200)return 'أدخل اسم الجهة المستلم منها';if(input.invoiceId)return 'ربط الفاتورة متاح للعميل المسجل فقط';if(!accounts.some(a=>a.id===input.creditAccountId))return 'اختر حساباً مقابلاً مناسباً للجهة الأخرى'}else return 'حدد نوع الجهة';return null}
